### ISSUE TITLE
Cannot compile on the latest Debian stable with rt-686-pae kernel

### ISSUE THREAD

**Issue by sanyock** [zfsonlinux/spl#218]
On the 686-pae kernel it fails to compile too
These are backported v3.2 kernels

Btw, on 64 bit kernel it compiles and runs fine on backported v3.2
But on the stable v2.6.32 64bit it hangs often with rsync

Always tried 32 bit userspace

**Comment by kernelOfTruth** [comment]
@ryao and news from you on this ?

Some news from my side:

```CONFIG_PREEMPT_RTB``` works ("basic" RT ?)

```CONFIG_PREEMPT_RT_FULL``` leads to the known error message ...

**Comment by behlendorf** [comment]
Closing this is believe to have been fixed in master and is awaiting verification.
