### ISSUE TITLE
error: Architecture is not included: ia64

### ISSUE THREAD

**Issue by jibanes** [zfsonlinux/spl#228]
Hello,

I've been trying to build SPL on ia64 without much success, as such:

root@hicks:~# make deb-utils deb-kmod
[...snip...]
tardir=spl-0.6.1 && /bin/bash /root/zfs/0.6.1/spl-0.6.1/config/missing --run tar chof - "$tardir" | GZIP=--best gzip -c >spl-0.6.1.tar.gz
{ test ! -d "spl-0.6.1" || { find "spl-0.6.1" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -fr "spl-0.6.1"; }; }
make[2]: Entering directory `/root/zfs/0.6.1/spl-0.6.1'
make[2]: Leaving directory `/root/zfs/0.6.1/spl-0.6.1'
sh: %{__id_u}: not found
Wrote: /tmp/spl-build-root-qO5kOUn5/SRPMS/spl-0.6.1-1.src.rpm
make[1]: Leaving directory `/root/zfs/0.6.1/spl-0.6.1'
make  pkg="spl" \
                def='--define "_without_debug 1" --define "_with_debug_log 1" --define "_with_debug_kmem 1" --define "_without_debug_kmem_tracking 1" ' rpm-common
make[1]: Entering directory `/root/zfs/0.6.1/spl-0.6.1'
make[2]: Entering directory `/root/zfs/0.6.1/spl-0.6.1'
make[2]: Leaving directory `/root/zfs/0.6.1/spl-0.6.1'
Installing spl-0.6.1-1.src.rpm
sh: %{__id_u}: not found
error: Architecture is not included: ia64
make[1]: *** [rpm-common] Error 1
make[1]: Leaving directory `/root/zfs/0.6.1/spl-0.6.1'
make: *** [rpm-utils] Error 2
root@hicks:~# uname -a
Linux hicks 2.6.34.14 #3 SMP Tue Mar 12 17:39:54 PDT 2013 ia64 GNU/Linux

I was wondering what was causing this error.

Thanks,
Jerome

**Comment by behlendorf** [comment]
Support for ia64 is not regularly tested but this is believed to work.  We'll open a new bug if this is not the case.
