### ISSUE TITLE
make rpm fails on Suse

### ISSUE THREAD

**Issue by ghost** [zfsonlinux/spl#230]
make rpm
make  pkg="spl-kmod" \
                def='--define "build_src_rpm 1" ' srpm-common
make[1]: Entering directory `/image64/coghead/ZFS/spl-0.6.1'
{ test ! -d "spl-0.6.1" || { find "spl-0.6.1" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -fr "spl-0.6.1"; }; }
test -d "spl-0.6.1" || mkdir "spl-0.6.1"
 (cd include && make  top_distdir=../spl-0.6.1 distdir=../spl-0.6.1/include \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory`/image64/coghead/ZFS/spl-0.6.1/include'
 (cd fs && make  top_distdir=../../spl-0.6.1 distdir=../../spl-0.6.1/include/fs \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/image64/coghead/ZFS/spl-0.6.1/include/fs'
make[3]: Leaving directory`/image64/coghead/ZFS/spl-0.6.1/include/fs'
 (cd linux && make  top_distdir=../../spl-0.6.1 distdir=../../spl-0.6.1/include/linux \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/image64/coghead/ZFS/spl-0.6.1/include/linux'
make[3]: Leaving directory`/image64/coghead/ZFS/spl-0.6.1/include/linux'
 (cd rpc && make  top_distdir=../../spl-0.6.1 distdir=../../spl-0.6.1/include/rpc \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/image64/coghead/ZFS/spl-0.6.1/include/rpc'
make[3]: Leaving directory`/image64/coghead/ZFS/spl-0.6.1/include/rpc'
 (cd sharefs && make  top_distdir=../../spl-0.6.1 distdir=../../spl-0.6.1/include/sharefs \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/image64/coghead/ZFS/spl-0.6.1/include/sharefs'
make[3]: Leaving directory`/image64/coghead/ZFS/spl-0.6.1/include/sharefs'
 (cd sys && make  top_distdir=../../spl-0.6.1 distdir=../../spl-0.6.1/include/sys \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)  
make[3]: Entering directory `/image64/coghead/ZFS/spl-0.6.1/include/sys'                                  
 (cd fm && make  top_distdir=../../../spl-0.6.1 distdir=../../../spl-0.6.1/include/sys/fm \               
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)                            
make[4]: Entering directory`/image64/coghead/ZFS/spl-0.6.1/include/sys/fm'  
make[4]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1/include/sys/fm'                                
 (cd fs && make  top_distdir=../../../spl-0.6.1 distdir=../../../spl-0.6.1/include/sys/fs \               
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)                            
make[4]: Entering directory`/image64/coghead/ZFS/spl-0.6.1/include/sys/fs'  
make[4]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1/include/sys/fs'                                
 (cd sysevent && make  top_distdir=../../../spl-0.6.1 distdir=../../../spl-0.6.1/include/sys/sysevent \   
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)                            
make[4]: Entering directory`/image64/coghead/ZFS/spl-0.6.1/include/sys/sysevent'  
make[4]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1/include/sys/sysevent'                          
make[3]: Leaving directory`/image64/coghead/ZFS/spl-0.6.1/include/sys'  
 (cd util && make  top_distdir=../../spl-0.6.1 distdir=../../spl-0.6.1/include/util \  
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)  
make[3]: Entering directory `/image64/coghead/ZFS/spl-0.6.1/include/util'                                 
make[3]: Leaving directory`/image64/coghead/ZFS/spl-0.6.1/include/util'  
 (cd vm && make  top_distdir=../../spl-0.6.1 distdir=../../spl-0.6.1/include/vm \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/image64/coghead/ZFS/spl-0.6.1/include/vm'
make[3]: Leaving directory`/image64/coghead/ZFS/spl-0.6.1/include/vm'
make[2]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1/include'
 (cd rpm && make  top_distdir=../spl-0.6.1 distdir=../spl-0.6.1/rpm \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory`/image64/coghead/ZFS/spl-0.6.1/rpm'
 (cd fedora && make  top_distdir=../../spl-0.6.1 distdir=../../spl-0.6.1/rpm/fedora \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/image64/coghead/ZFS/spl-0.6.1/rpm/fedora'
make[3]: Leaving directory`/image64/coghead/ZFS/spl-0.6.1/rpm/fedora'
 (cd generic && make  top_distdir=../../spl-0.6.1 distdir=../../spl-0.6.1/rpm/generic \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/image64/coghead/ZFS/spl-0.6.1/rpm/generic'
make[3]: Leaving directory`/image64/coghead/ZFS/spl-0.6.1/rpm/generic'
make[2]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1/rpm'
 (cd lib && make  top_distdir=../spl-0.6.1 distdir=../spl-0.6.1/lib \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory`/image64/coghead/ZFS/spl-0.6.1/lib'
make[2]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1/lib'
 (cd cmd && make  top_distdir=../spl-0.6.1 distdir=../spl-0.6.1/cmd \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory`/image64/coghead/ZFS/spl-0.6.1/cmd'
make[2]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1/cmd'
 (cd man && make  top_distdir=../spl-0.6.1 distdir=../spl-0.6.1/man \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory`/image64/coghead/ZFS/spl-0.6.1/man'
 (cd man1 && make  top_distdir=../../spl-0.6.1 distdir=../../spl-0.6.1/man/man1 \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/image64/coghead/ZFS/spl-0.6.1/man/man1'
make[3]: Leaving directory`/image64/coghead/ZFS/spl-0.6.1/man/man1'
make[2]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1/man'
 (cd scripts && make  top_distdir=../spl-0.6.1 distdir=../spl-0.6.1/scripts \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory`/image64/coghead/ZFS/spl-0.6.1/scripts'
make[2]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1/scripts'
 (cd module && make  top_distdir=../spl-0.6.1 distdir=../spl-0.6.1/module \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory`/image64/coghead/ZFS/spl-0.6.1/module'
list='spl splat'; for subdir in $list; do \
                (find ../module/$subdir -name '_.c' -o -name '_.h' |\
                 xargs /bin/cp -t $distdir/$subdir); \
        done
make[2]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1/module'
make  \
          top_distdir="spl-0.6.1" distdir="spl-0.6.1" \
          dist-hook
make[2]: Entering directory`/image64/coghead/ZFS/spl-0.6.1'
sed -i 's/Release:[[:print:]]*/Release:      1/' \
                spl-0.6.1/META
make[2]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1'
test -n "" \
        || find "spl-0.6.1" -type d ! -perm -755 \
                -exec chmod u+rwx,go+rx {} \; -o \
          ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
          ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
          ! -type d ! -perm -444 -exec /bin/sh /coghead/ZFS/spl-0.6.1/config/install-sh -c -m a+r {} {} \; \
        || chmod -R a+r "spl-0.6.1"
tardir=spl-0.6.1 && /bin/sh /coghead/ZFS/spl-0.6.1/config/missing --run tar chof - "$tardir" | GZIP=--best gzip -c >spl-0.6.1.tar.gz
{ test ! -d "spl-0.6.1" || { find "spl-0.6.1" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -fr "spl-0.6.1"; }; }
make[2]: Entering directory`/image64/coghead/ZFS/spl-0.6.1'
make[2]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1'
sh: -c: line 5: syntax error: unexpected end of file
Wrote: /tmp/spl-build-root-Ne43VhQW/SRPMS/spl-kmod-0.6.1-1.src.rpm
make[1]: Leaving directory`/image64/coghead/ZFS/spl-0.6.1'
make  pkg="spl-kmod" \
                def='--define "_without_debug 1" --define "_with_debug_log 1" --define "_with_debug_kmem 1" --define "_without_debug_kmem_tracking 1" --define "kernels 3.0.58-0.6.6-ec2"' rpm-common
make[1]: Entering directory `/image64/coghead/ZFS/spl-0.6.1'
make[2]: Entering directory`/image64/coghead/ZFS/spl-0.6.1'
make[2]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1'
Installing spl-kmod-0.6.1-1.src.rpm
sh: -c: line 5: syntax error: unexpected end of file
Executing(%prep): /bin/sh -e /tmp/spl-build-root-lWw7aWM7/TMP/rpm-tmp.51785
- umask 022
- cd /tmp/spl-build-root-lWw7aWM7/BUILD
- bash /tmp/spl-build-root-lWw7aWM7/SOURCES/kmodtool --target x86_64 --kmodname spl-kmod --devel --for-kernels 3.0.58-0.6.6-ec2
  %package       -n kmod-spl-3.0.58-0.6.6-ec2
  Summary:          spl kernel module(s) for 3.0.58-0.6.6-ec2
  Group:            System Environment/Kernel
  Provides:         kernel-modules-for-kernel = 3.0.58-0.6.6-ec2
  Provides:         kmod-spl-uname-r = 3.0.58-0.6.6-ec2
  Provides:         spl-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
  Requires:         spl-kmod-common >= %{?epoch:%{epoch}:}%{version}
  Requires(post):   /sbin/depmod
  Requires(postun): /sbin/depmod
  %{?KmodsRequires:Requires: %{KmodsRequires}-uname-r = 3.0.58-0.6.6-ec2}
  %{?KmodsBuildRequires:BuildRequires: %{KmodsBuildRequires}-uname-r = 3.0.58-0.6.6-ec2}
  %{?KmodsBuildRequires:BuildRequires: %{KmodsBuildRequires}}
  %post          -n kmod-spl-3.0.58-0.6.6-ec2
  [[ "3.0.58-0.6.6-ec2" == "3.0.58-0.6.6-ec2"  ]] && /sbin/depmod -a > /dev/null || :
  %postun        -n kmod-spl-3.0.58-0.6.6-ec2
  [[ "3.0.58-0.6.6-ec2" == "3.0.58-0.6.6-ec2"  ]] && /sbin/depmod -a > /dev/null || :

%description  -n kmod-spl-3.0.58-0.6.6-ec2
This package provides the spl kernel modules built for the Linux
kernel 3.0.58-0.6.6-ec2 for the %{_target_cpu} family of processors.
%files        -n kmod-spl-3.0.58-0.6.6-ec2
%defattr(644,root,root,755)
%dir /lib/modules/3.0.58-0.6.6-ec2/extra
/lib/modules/3.0.58-0.6.6-ec2/extra/spl/

%package       -n kmod-spl-devel-3.0.58-0.6.6-ec2
Summary:          spl kernel module(s) devel for 3.0.58-0.6.6-ec2
Group:            System Environment/Kernel
Requires:         spl-devel-kmod-common = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:         spl-devel-kmod = %{?epoch:%{epoch}:}%{version}-%{release}
Provides:         spl-devel-kmod-uname-r = 3.0.58-0.6.6-ec2
%description  -n kmod-spl-devel-3.0.58-0.6.6-ec2
This package provides objects and symbols required to build kernel modules
which depend on the spl kernel modules built for the Linux
kernel 3.0.58-0.6.6-ec2 for the %{_target_cpu} family of processors.
%files        -n kmod-spl-devel-3.0.58-0.6.6-ec2
%defattr(644,root,root,755)
%{_usrsrc}/spl-%{version}/3.0.58-0.6.6-ec2

%package       -n kmod-spl-devel
Summary:          spl kernel module(s) devel common
Group:            System Environment/Kernel
Provides:         spl-devel-kmod-common = %{?epoch:%{epoch}:}%{version}-%{release}

%description  -n kmod-spl-devel
This package provides the common header files to build kernel modules
which depend on the spl kernel module.
%files        -n kmod-spl-devel
%defattr(644,root,root,755)
%{_usrsrc}/spl-%{version}
%exclude %{_usrsrc}/spl-%{version}/3.0.58-0.6.6-ec2

%global kmodinstdir_prefix  /lib/modules/
%global kmodinstdir_postfix /extra/spl/
%global kernel_versions     3.0.58-0.6.6-ec2___/lib/modules/3.0.58-0.6.6-ec2/build/
- cd /tmp/spl-build-root-lWw7aWM7/BUILD
- rm -rf spl-kmod-0.6.1
- /bin/mkdir -p spl-kmod-0.6.1
- cd spl-kmod-0.6.1
- /usr/bin/gzip -dc /tmp/spl-build-root-lWw7aWM7/SOURCES/spl-0.6.1.tar.gz
- tar -xf -
- STATUS=0
- '[' 0 -ne 0 ']'
  ++ /usr/bin/id -u
- '[' 0 = 0 ']'
- /bin/chown -Rhf root .
  ++ /usr/bin/id -u
- '[' 0 = 0 ']'
- /bin/chgrp -Rhf root .
- /bin/chmod -Rf a+rX,u+w,g-w,o-w .
- for kernel_version in 3.0.58-0.6.6-ec2___/lib/modules/3.0.58-0.6.6-ec2/build/
- /bin/mkdir _kmod_build_3.0.58-0.6.6-ec2
- exit 0
  Executing(%build): /bin/sh -e /tmp/spl-build-root-lWw7aWM7/TMP/rpm-tmp.51785
- umask 022
- cd /tmp/spl-build-root-lWw7aWM7/BUILD
- /bin/rm -rf /tmp/spl-build-root-lWw7aWM7/TMP/spl-kmod-0.6.1-1-root-root
  ++ dirname /tmp/spl-build-root-lWw7aWM7/TMP/spl-kmod-0.6.1-1-root-root
- /bin/mkdir -p /tmp/spl-build-root-lWw7aWM7/TMP
- /bin/mkdir /tmp/spl-build-root-lWw7aWM7/TMP/spl-kmod-0.6.1-1-root-root
- cd spl-kmod-0.6.1
- for kernel_version in 3.0.58-0.6.6-ec2___/lib/modules/3.0.58-0.6.6-ec2/build/
- cd _kmod_build_3.0.58-0.6.6-ec2
- CFLAGS='-O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables'
- export CFLAGS
- CXXFLAGS='-O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables'
- export CXXFLAGS
- FFLAGS='-O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables'
- export FFLAGS
- ./configure --host=x86_64-suse-linux-gnu --build=x86_64-suse-linux-gnu --target=x86_64-suse-linux --program-prefix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/lib64 --localstatedir=/var --sharedstatedir=/usr/com --mandir=/usr/share/man --infodir=/usr/share/info --with-config=kernel --with-linux= --with-linux-obj=/lib/modules/3.0.58-0.6.6-ec2/build --disable-debug --enable-debug-log --enable-debug-kmem --disable-debug-kmem-tracking --disable-atomic-spinlocks
  /tmp/spl-build-root-lWw7aWM7/TMP/rpm-tmp.51785: line 33: ./configure: No such file or directory
  error: Bad exit status from /tmp/spl-build-root-lWw7aWM7/TMP/rpm-tmp.51785 (%build)

RPM build errors:
    Bad exit status from /tmp/spl-build-root-lWw7aWM7/TMP/rpm-tmp.51785 (%build)
make[1]: **\* [rpm-common] Error 1
make[1]: Leaving directory `/image64/coghead/ZFS/spl-0.6.1'
make: **\* [rpm-kmod] Error 2

This is the content of  /tmp/spl-build-root-lWw7aWM7/TMP/rpm-tmp.51785:

cat  /tmp/spl-build-root-lWw7aWM7/TMP/rpm-tmp.51785
# !/bin/sh

  RPM_SOURCE_DIR="/tmp/spl-build-root-lWw7aWM7/SOURCES"
  RPM_BUILD_DIR="/tmp/spl-build-root-lWw7aWM7/BUILD"
  RPM_OPT_FLAGS="-O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables"
  RPM_ARCH="x86_64"
  RPM_OS="linux"
  export RPM_SOURCE_DIR RPM_BUILD_DIR RPM_OPT_FLAGS RPM_ARCH RPM_OS
  RPM_DOC_DIR="/usr/share/doc/packages"
  export RPM_DOC_DIR
  RPM_PACKAGE_NAME="spl-kmod"
  RPM_PACKAGE_VERSION="0.6.1"
  RPM_PACKAGE_RELEASE="1"
  export RPM_PACKAGE_NAME RPM_PACKAGE_VERSION RPM_PACKAGE_RELEASE
  RPM_BUILD_ROOT="/tmp/spl-build-root-lWw7aWM7/TMP/spl-kmod-0.6.1-1-root-root"
  export RPM_BUILD_ROOT

  set -x
  umask 022
  cd "/tmp/spl-build-root-lWw7aWM7/BUILD"
  /bin/rm -rf "$RPM_BUILD_ROOT"
  /bin/mkdir -p `dirname "$RPM_BUILD_ROOT"`
  /bin/mkdir "$RPM_BUILD_ROOT"
cd 'spl-kmod-0.6.1'
for kernel_version in 3.0.58-0.6.6-ec2___/lib/modules/3.0.58-0.6.6-ec2/build/; do
    cd _kmod_build_${kernel_version%___*}
        pwd 
        exit

  CFLAGS="${CFLAGS:--O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables}" ; export CFLAGS ; 
  CXXFLAGS="${CXXFLAGS:--O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables}" ; export CXXFLAGS ; 
  FFLAGS="${FFLAGS:--O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables}" ; export FFLAGS ; 
  ./configure --host=x86_64-suse-linux-gnu --build=x86_64-suse-linux-gnu \
        --target=x86_64-suse-linux \
        --program-prefix= \
        --prefix=/usr \
        --exec-prefix=/usr \
        --bindir=/usr/bin \
        --sbindir=/usr/sbin \
        --sysconfdir=/etc \
        --datadir=/usr/share \
        --includedir=/usr/include \
        --libdir=/usr/lib64 \
        --libexecdir=/usr/lib64 \
        --localstatedir=/var \
        --sharedstatedir=/usr/com \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --with-config=kernel \
        --with-linux=\
         \
        --with-linux-obj="/lib/modules/${kernel_version%___*}/build" \
        --disable-debug \
        --enable-debug-log \
        --enable-debug-kmem \
        --disable-debug-kmem-tracking \
        --disable-atomic-spinlocks
    make -j2
    cd ..
done

exit 0

**Comment by aaronknister** [comment]
For what it's worth I was able to work around these on SLES 11 SP3 LTSS by adding:

`lndir ../%{module}-%{version} .`

before the `%configure` in the rpm/generic/*-kmod.spec.in files before running `./configure` and `make rpm`.
