### ISSUE TITLE
BUG# DEBian (wheezy ) 7.0  arch=arm6 ( RPI )  SPL/ ZFS modules wrong format - not loaded

### ISSUE THREAD

**Issue by hvenzke** [zfsonlinux/spl#236]
Trying to get SPL and ZFS compiled on RPI arm debian 7 , kenrel 3.8.12

<pre>

 insmod /lib/modules/3.8.12-4-raspberrypi-g1f8de6a/extra/spl/spl.ko
Error: could not insert module /lib/modules/3.8.12-4-raspberrypi-g1f8de6a/extra/spl/spl.ko: Invalid module format
root@smb:/usr/src/GIT/zfsonlinux/spl# insmod /lib/modules/3.8.12-4-raspberrypi-g1f8de6a/extra/splat/splat.ko
Error: could not insert module /lib/modules/3.8.12-4-raspberrypi-g1f8de6a/extra/splat/splat.ko: Invalid module format
root@smb:/usr/src/GIT/zfsonlinux/spl# file /lib/modules/3.8.12-4-raspberrypi-g1f8de6a/extra/splat/splat.ko
/lib/modules/3.8.12-4-raspberrypi-g1f8de6a/extra/splat/splat.ko: ELF 32-bit LSB relocatable, ARM, version 1 (SYSV), BuildID[sha1]=0x0a9530374177206f82bcda552d0ce1f0dbe6d2f3, not stripped

uname -a
Linux smb 3.8.12+ #440 PREEMPT Wed May 8 23:14:03 BST 2013 armv6l GNU/Linux

[ 4787.271245] spl: disagrees about version of symbol module_layout
[ 6793.190615] spl: disagrees about version of symbol module_layout
[ 7028.702137] spl: disagrees about version of symbol module_layout
[ 7036.918976] splat: disagrees about version of symbol module_layout
</pre>

SPL failed to load 

<pre>
make[1]: Entering directory `/usr/src/GIT/zfsonlinux/zfs/module'
make -C /usr/src/linux SUBDIRS=`pwd` modules_install \
                INSTALL_MOD_PATH= \
                INSTALL_MOD_DIR=extra
make[2]: Entering directory `/usr/src/rpi-3.8.12.y'
  DEPMOD  3.8.12-4-raspberrypi-g1f8de6a
WARNING: could not open /lib/modules/3.8.12-4-raspberrypi-g1f8de6a/modules.order: No such file or directory
WARNING: /lib/modules/3.8.12-4-raspberrypi-g1f8de6a/extra/spl/spl.ko needs unknown symbol zlib_deflateEnd
WARNING: /lib/modules/3.8.12-4-raspberrypi-g1f8de6a/extra/spl/spl.ko needs unknown symbol zlib_deflate
WARNING: /lib/modules/3.8.12-4-raspberrypi-g1f8de6a/extra/spl/spl.ko needs unknown symbol zlib_deflate_workspacesize
WARNING: /lib/modules/3.8.12-4-raspberrypi-g1f8de6a/extra/spl/spl.ko needs unknown symbol zlib_deflateInit2
WARNING: could not open /lib/modules/3.8.12-4-raspberrypi-g1f8de6a/modules.builtin: No such file or directory
make[2]: Leaving directory `/usr/src/rpi-3.8.12.y'
kmoddir=/lib/modules/3.8.12-4-raspberrypi-g1f8de6a; \
        if [ -n $kmoddir ]; then \
                find $kmoddir -name 'modules.*' | xargs rm -f; \
        fi
sysmap=/boot/System.map-3.8.12-4-raspberrypi-g1f8de6a; \
        if [ -f $sysmap ]; then \
                depmod -ae -F $sysmap 3.8.12-4-raspberrypi-g1f8de6a; \
        fi
make[1]: Leaving directory `/usr/src/GIT/zfsonlinux/zfs/module'
make[1]: Entering directory `/usr/src/GIT/zfsonlinux/zfs'
make[1]: *** No rule to make target `module/Module.symvers', needed by `all-am'.  Stop.
make[1]: Leaving directory `/usr/src/GIT/zfsonlinux/zfs'
make: *** [install-recursive] Error 1

</pre> 

ZFS failed as well.

<pre>

$ ls /lib/modules/3.8.12+
kernel             modules.builtin      modules.dep      modules.ieee1394map  modules.ofmap   modules.seriomap  modules.symbols.bin
modules.alias      modules.builtin.bin  modules.dep.bin  modules.inputmap     modules.order   modules.softdep   modules.usbmap
modules.alias.bin  modules.ccwmap       modules.devname  modules.isapnpmap    modules.pcimap  modules.symbols
$:/usr/src/GIT/zfsonlinux# ls /lib/modules/3.8.12+/modules.order
/lib/modules/3.8.12+/modules.order
$ /usr/src/GIT/zfsonlinux#
</pre>

caused i.e  "configure" failed  to determine where are the Modules installd.

What options i have to say where it shuold be installed ?
there seems no configure option for that.

<pre>
ecking linux distribution... debian
checking default package type... deb
checking whether rpm is available... yes (4.10.0)
checking whether rpmbuild is available... yes (4.10.0)
checking whether spec files are available... yes (rpm/generic/*.spec.in)
checking whether dpkg is available... yes (1.16.10)
checking whether dpkg-buildpackage is available... yes (1.16.10.)
checking whether alien is available... yes (8.87)
checking spl config... all
checking kernel source directory... /usr/src/linux
checking kernel build directory... /usr/src/linux
checking kernel source version... 3.8.12-4-raspberrypi-g1f8de6a
checking kernel file name for module symbols... Module.symvers
checking whether debugging is enabled... no
checking whether basic debug logging is enabled... yes
checking whether basic kmem accounting is enabled... yes
checking whether detailed kmem tracking is enabled... no
checking whether modules can be built... yes
</pre>

checking kernel source version wrong.  KVER =`uname -r` as regulary

**Comment by behlendorf** [comment]
This now works and builds are now done for every commit using arm to prevent regressions.

http://build.zfsonlinux.org/builders/Debian%208%20arm%20%28BUILD%29
