### ISSUE TITLE
spl 0.6.1 build failed with openwrt-trunk (kernel 3.8.13)

### ISSUE THREAD

**Issue by dilruacs** [zfsonlinux/spl#248]
I am trying to package SPL and ZFS for OpenWRT (trunk) and I get the following error from the configure script:

./configure --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls   --with-linux=/usr/src/OpenWRT/build_dir/target-x86_64_uClibc-0.9.33.2/linux-uml/linux-3.8.13 --with-linux-obj=/usr/src/OpenWRT/build_dir/target-x86_64_uClibc-0.9.33.2/linux-uml/linux-3.8.13
configure: WARNING: unrecognized options: --disable-nls
configure: loading site script /usr/src/OpenWRT/include/site/x86_64-openwrt-linux-uclibc
checking metadata... META file
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-openwrt-linux-gnu
checking target system type... x86_64-openwrt-linux-gnu
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-openwrt-linux-strip... x86_64-openwrt-linux-uclibc-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for x86_64-openwrt-linux-gcc... x86_64-openwrt-linux-uclibc-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-openwrt-linux-uclibc-gcc accepts -g... yes
checking for x86_64-openwrt-linux-uclibc-gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of x86_64-openwrt-linux-uclibc-gcc... gcc3
checking for a sed that does not truncate output... /usr/src/OpenWRT/staging_dir/host/bin/sed
checking for grep that handles long lines and -e... /usr/src/OpenWRT/staging_dir/host/bin/grep
checking for egrep... /usr/src/OpenWRT/staging_dir/host/bin/grep -E
checking for fgrep... /usr/src/OpenWRT/staging_dir/host/bin/grep -F
checking for ld used by x86_64-openwrt-linux-uclibc-gcc... x86_64-openwrt-linux-uclibc-ld
checking if the linker (x86_64-openwrt-linux-uclibc-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... x86_64-openwrt-linux-uclibc-nm
checking the name lister (x86_64-openwrt-linux-uclibc-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 3458764513820540925
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for x86_64-openwrt-linux-uclibc-ld option to reload object files... -r
checking for x86_64-openwrt-linux-objdump... x86_64-openwrt-linux-uclibc-objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-openwrt-linux-ar... x86_64-openwrt-linux-uclibc-ar
checking for x86_64-openwrt-linux-strip... (cached) x86_64-openwrt-linux-uclibc-strip
checking for x86_64-openwrt-linux-ranlib... x86_64-openwrt-linux-uclibc-ranlib
checking command to parse x86_64-openwrt-linux-uclibc-nm output from x86_64-openwrt-linux-uclibc-gcc object... ok
checking how to run the C preprocessor... x86_64-openwrt-linux-uclibc-gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if x86_64-openwrt-linux-uclibc-gcc supports -fno-rtti -fno-exceptions... no
checking for x86_64-openwrt-linux-uclibc-gcc option to produce PIC... -fPIC -DPIC
checking if x86_64-openwrt-linux-uclibc-gcc PIC flag -fPIC -DPIC works... yes
checking if x86_64-openwrt-linux-uclibc-gcc static flag -static works... yes
checking if x86_64-openwrt-linux-uclibc-gcc supports -c -o file.o... yes
checking if x86_64-openwrt-linux-uclibc-gcc supports -c -o file.o... (cached) yes
checking whether the x86_64-openwrt-linux-uclibc-gcc linker (x86_64-openwrt-linux-uclibc-ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking spl license... GPL
checking linux distribution... debian
checking default package type... deb
checking whether rpm is available... no
checking whether rpmbuild is available... no
checking whether spec files are available... yes (rpm/generic/*.spec.in)
checking whether dpkg is available... yes (1.16.10)
checking whether dpkg-buildpackage is available... yes (1.16.10.)
checking whether alien is available... no
checking spl config... all
checking kernel source directory... /usr/src/OpenWRT/build_dir/target-x86_64_uClibc-0.9.33.2/linux-uml/linux-3.8.13
checking kernel build directory... /usr/src/OpenWRT/build_dir/target-x86_64_uClibc-0.9.33.2/linux-uml/linux-3.8.13
checking kernel source version... 3.8.13
checking kernel file name for module symbols... Module.symvers
checking whether debugging is enabled... no
checking whether basic debug logging is enabled... yes
checking whether basic kmem accounting is enabled... yes
checking whether detailed kmem tracking is enabled... no
checking whether modules can be built... yes
checking whether atomic types use spinlocks... no
checking whether kernel defines atomic64_t... yes
checking whether kernel defines atomic64_cmpxchg... yes
checking whether kernel defines atomic64_xchg... yes
checking whether kernel defines uintptr_t... yes
checking whether register_sysctl_table() wants 2 args... no
checking whether set_shrinker() available... no
checking whether shrinker callback wants 3 args... no
checking whether struct path used in struct nameidata... yes
checking whether task_curr() is available... no
checking whether unnumbered sysctl support exists... no
checking whether struct ctl_table has ctl_name... no
checking whether fls64() is available... yes
checking whether device_create() is available... yes
checking whether device_create() wants 5 args... no
checking whether class_device_create() is available... no
checking whether set_normalized_timespec() is available as export... yes
checking whether set_normalized_timespec() is an inline... yes
checking whether timespec_sub() is available... yes
checking whether init_utsname() is available... yes
checking whether header linux/uaccess.h exists... yes
checking whether kmalloc_node() is available... yes
checking whether monotonic_clock() is available... no
checking whether struct inode has i_mutex... yes
checking whether struct mutex has owner... no
checking whether struct mutex owner is a task_struct... no
checking whether mutex_lock_nested() is available... yes
checking whether on_each_cpu() wants 3 args... yes
checking whether kallsyms_lookup_name() is available... no
checking whether get_vmalloc_info() is available... no
checking whether symbol *_pgdat exist... yes
checking whether first_online_pgdat() is available... no
checking whether next_online_pgdat() is available... no
checking whether next_zone() is available... no
checking whether pgdat_list is available... no
checking whether global_page_state() is available... yes
checking whether page state NR_FREE_PAGES is available... yes
checking whether page state NR_INACTIVE is available... no
checking whether page state NR_INACTIVE_ANON is available... yes
checking whether page state NR_INACTIVE_FILE is available... yes
checking whether page state NR_ACTIVE is available... no
checking whether page state NR_ACTIVE_ANON is available... yes
checking whether page state NR_ACTIVE_FILE is available... yes
checking whether symbol get_zone_counts is needed... no
checking whether user_path_dir() is available... no
checking whether set_fs_pwd() is available... no
checking whether set_fs_pwd() requires const struct path *... configure: error: unknown

**Comment by mailinglists35** [comment]
@dilruacs have you produced usable builds? I am interested to try them out!
