### ISSUE TITLE
Discrepancy between in-tree and out-of-tree builds

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/spl#251]
I pulled an early version zfsonlinux/spl#246 as well as behlendorf/zfs@91e2603bf06fb2b89c58fc5e7799364a760a405b and dweeezil/zfs@7698fda5b5437da5a8c0a0d425f02b1cc991dbd3 into gentoo-next for testing. One person using it had a build failure when he attempted to build the SPL and ZFS modules as part of the kernel source tree. It had multiple errors of this kind:

```
fs/zfs/nvpair/fnvpair.c:478:2: error: 'uintmax_t' undeclared (first use in this function)
```

This did not occur when building out-of-tree. The original version of zfsonlinux/spl#246 used uintmax_t in the VERIFY0 macro. The kernel source code does not use uintmax_t and it appears that any use of it inside the kernel causes a build failure. This suggests that the flags being passed to the C preprocessor by the kernel build system differs between in-tree and out-of-tree builds. I suspect that GCC's headers are being processed in addition to the kernel's headers when builds are out-of-tree.

I am filing this issue to track it. I suspect that @dechamps might be interested in this.

**Comment by behlendorf** [comment]
Closing, in-tree and out-of-tree builder are both now running regularly without issue.
