### ISSUE TITLE
Unmounts all zfs filesystems after scrub

### ISSUE THREAD

**Issue by traustitj** [zfsonlinux/spl#263]
Every time I do a scrub on my filesystem, it unmounts after use.
By reloading the zfs process in /etc/init.d/zfs the issue is fixed

These are the versions I have installed

zfs-release-1-2.el6.noarch
zfs-dracut-0.6.1-1.el6.x86_64
dkms-2.2.0.3-2.zfs1.el6.noarch
zfs-test-0.6.1-1.el6.x86_64
zfs-dkms-0.6.1-2.el6.noarch
zfs-0.6.1-1.el6.x86_64

On centos 6.4, kernel : 2.6.32-358.11.1.el6.x86_64

Will happily give out information as requested.

This happens every time. If you do 'zfs list' you get no results, but zpool list gives correct results, as does zpool status.

**Comment by behlendorf** [comment]
Closing, not enough information.
