### ISSUE TITLE
spl_kmem_cache spinning in shrink_mem_cgroup_zone

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/spl#271]
Kernel 3.4.49 + SPL issue 268 patch manually applied.
Machine: 16 GB of RAM, 2-core Xeon (Core2 Duo based) single-socket CPU.

<pre>
# top

top - 06:03:21 up 5 days, 19:01,  2 users,  load average: 73.51, 73.44, 73.15
Tasks: 340 total,   2 running, 334 sleeping,   0 stopped,   4 zombie
Cpu(s):  0.0%us, 51.1%sy,  0.0%ni,  0.0%id, 48.9%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  16417360k total, 11000412k used,  5416948k free,     1772k buffers
Swap:  2097148k total,   677328k used,  1419820k free,     7540k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 3275 root      39  19     0    0    0 R 100.0  0.0 944:14.73 spl_kmem_cache/
 3871 root      20   0 15208 1380  876 R  2.2  0.0   0:00.02 top
    1 root      20   0 19400  224    0 S  0.0  0.0   0:00.79 init

# echo t > /proc/sysrq-trigger
lsb_release     D 0000000000000001     0  3371   3339 0x00000000
 ffff88034b01b750 0000000000000082 ffff8804194d2890 ffff88034b01a010
 ffff880072816700 0000000000010a40 ffff88034b01bfd8 0000000000004000
 ffff88034b01bfd8 0000000000010a40 ffff88041d864060 ffff880072816700
Call Trace:
 [&lt;ffffffffa00e4c39&gt;] ? arc_buf_eviction_needed+0x62/0x6d [zfs]
 [&lt;ffffffffa00eca32&gt;] ? dbuf_rele_and_unlock+0x19f/0x1a4 [zfs]
 [&lt;ffffffffa00ecd63&gt;] ? dmu_buf_rele+0x25/0x2c [zfs]
 [&lt;ffffffffa0100cb9&gt;] ? dnode_rele+0x56/0x62 [zfs]
 [&lt;ffffffff8130e982&gt;] schedule+0x5f/0x61
 [&lt;ffffffff8130ebbc&gt;] schedule_preempt_disabled+0x9/0xb
 [&lt;ffffffff8130d438&gt;] __mutex_lock_slowpath+0xde/0x123
 [&lt;ffffffffa011fda5&gt;] ? sa_handle_destroy+0x8a/0x8e [zfs]
 [&lt;ffffffff8130d2d2&gt;] mutex_lock+0x16/0x27
 [&lt;ffffffffa00e7f29&gt;] arc_evict+0x62/0x517 [zfs]
 [&lt;ffffffffa01673e2&gt;] ? zfs_inode_destroy+0xec/0xf5 [zfs]
 [&lt;ffffffffa0172c02&gt;] ? zpl_inode_destroy+0x9/0xb [zfs]
 [&lt;ffffffff810d120a&gt;] ? evict+0x14c/0x155
 [&lt;ffffffffa00e889e&gt;] arc_adjust_meta+0x4c/0x194 [zfs]
 [&lt;ffffffffa0172ab9&gt;] zpl_free_cached_objects+0x15/0x17 [zfs]
 [&lt;ffffffff810bf447&gt;] prune_super+0x102/0x158
 [&lt;ffffffff8108a388&gt;] shrink_slab+0x122/0x19c
 [&lt;ffffffff8108b267&gt;] do_try_to_free_pages+0x34d/0x4e4
 [&lt;ffffffff8108b4e4&gt;] try_to_free_pages+0x68/0x6a
 [&lt;ffffffff810837e9&gt;] __alloc_pages_nodemask+0x4cf/0x75c
 [&lt;ffffffff810ae16d&gt;] new_slab+0x65/0x1ee
 [&lt;ffffffff8102386f&gt;] ? flush_tlb_page+0x58/0x76
 [&lt;ffffffff810ae69a&gt;] __slab_alloc.clone.1+0x15c/0x239
 [&lt;ffffffff810d27d3&gt;] ? alloc_fdmem+0x1f/0x30
 [&lt;ffffffff810ae46a&gt;] ? kmem_cache_free+0x88/0x8d
 [&lt;ffffffff810ae838&gt;] __kmalloc+0xc1/0x114
 [&lt;ffffffff810d27d3&gt;] alloc_fdmem+0x1f/0x30
 [&lt;ffffffff810d285b&gt;] alloc_fdtable+0x77/0xd8
 [&lt;ffffffff810d29c7&gt;] dup_fd+0x10b/0x267
 [&lt;ffffffff81026aa2&gt;] copy_process+0x550/0x10f1
 [&lt;ffffffff810be42a&gt;] ? get_empty_filp+0x98/0x139
 [&lt;ffffffff8102788d&gt;] do_fork+0xe3/0x26c
 [&lt;ffffffff810331af&gt;] ? __set_task_blocked+0x60/0x67
 [&lt;ffffffff810331e7&gt;] ? set_current_blocked+0x31/0x45
 [&lt;ffffffff81008f03&gt;] sys_clone+0x23/0x25
 [&lt;ffffffff8130fef3&gt;] stub_clone+0x13/0x20
 [&lt;ffffffff8130fca2&gt;] ? system_call_fastpath+0x16/0x1b

# echo l > /proc/sysrq-trigger
CPU0:
 ffff88042fc03ef0 ffff88042fc03f08 0000000000000046 ffff88042fc03f68
 0000000000000001 ffff88041d859b40 ffff880417957aa0 ffff88042fc03f38
 ffffffff8100473a ffff88042fc03f58 ffffffff811d584a ffffffff81310e4c
Call Trace:
 &lt;IRQ&gt;  [&lt;ffffffff8100473a&gt;] ? show_stack+0x17/0x19
 [&lt;ffffffff811d584a&gt;] ? showacpu+0x48/0x5b
 [&lt;ffffffff81310e4c&gt;] ? call_softirq+0x1c/0x30
 [&lt;ffffffff810598d4&gt;] ? generic_smp_call_function_single_interrupt+0xc7/0xe9
 [&lt;ffffffff810187b2&gt;] ? smp_call_function_single_interrupt+0x22/0x31
 [&lt;ffffffff81310927&gt;] ? call_function_single_interrupt+0x67/0x70
 &lt;EOI&gt;  [&lt;ffffffff81089a88&gt;] ? shrink_inactive_list+0x26d/0x42a
 [&lt;ffffffff8108a026&gt;] ? shrink_mem_cgroup_zone+0x3e1/0x503
 [&lt;ffffffff810b6a7f&gt;] ? mem_cgroup_iter+0xf8/0x1c1
 [&lt;ffffffff8108a1a7&gt;] ? shrink_zone+0x5f/0x9a
 [&lt;ffffffff8108b138&gt;] ? do_try_to_free_pages+0x21e/0x4e4
 [&lt;ffffffff810830e2&gt;] ? get_page_from_freelist+0x477/0x4a8
 [&lt;ffffffff8108b4e4&gt;] ? try_to_free_pages+0x68/0x6a
 [&lt;ffffffff810837e9&gt;] ? __alloc_pages_nodemask+0x4cf/0x75c
 [&lt;ffffffff81083af2&gt;] ? __get_free_pages+0x12/0x41
 [&lt;ffffffffa0049839&gt;] ? kv_alloc+0x28/0x40 [spl]
 [&lt;ffffffffa0049882&gt;] ? spl_cache_grow_work+0x31/0x3bd [spl]
 [&lt;ffffffffa004c8ab&gt;] ? taskq_thread+0x2be/0x447 [spl]
 [&lt;ffffffff81048cfb&gt;] ? try_to_wake_up+0x219/0x219
 [&lt;ffffffffa004c5ed&gt;] ? task_expire+0xf6/0xf6 [spl]
 [&lt;ffffffff8103e65a&gt;] ? kthread+0x84/0x8c
 [&lt;ffffffff81310d54&gt;] ? kernel_thread_helper+0x4/0x10
 [&lt;ffffffff8103e5d6&gt;] ? kthread_freezable_should_stop+0x58/0x58
 [&lt;ffffffff81310d50&gt;] ? gs_change+0xb/0xb

# echo l > /proc/sysrq-trigger
CPU0:
 ffff88042fc03ef0 ffff88042fc03f08 0000000000000046 ffff88042fc03f68
 0000000000000001 0000000000000000 ffff880417957920 ffff88042fc03f38
 ffffffff8100473a ffff88042fc03f58 ffffffff811d584a ffffffff81310e4c
Call Trace:
 &lt;IRQ>  [&lt;ffffffff8100473a>] ? show_stack+0x17/0x19
 [&lt;ffffffff811d584a>] ? showacpu+0x48/0x5b
 [&lt;ffffffff81310e4c>] ? call_softirq+0x1c/0x30
 [&lt;ffffffff810598d4>] ? generic_smp_call_function_single_interrupt+0xc7/0xe9
 [&lt;ffffffff810187b2>] ? smp_call_function_single_interrupt+0x22/0x31
 [&lt;ffffffff81310927>] ? call_function_single_interrupt+0x67/0x70
 &lt;EOI>  [&lt;ffffffff81088ec5>] ? shrink_page_list+0x131/0x7e8
 [&lt;ffffffff8108817e>] ? update_isolated_counts+0x12a/0x139
 [&lt;ffffffff81089ac3>] ? shrink_inactive_list+0x2a8/0x42a
 [&lt;ffffffff8108a026>] ? shrink_mem_cgroup_zone+0x3e1/0x503
 [&lt;ffffffff810b6a7f>] ? mem_cgroup_iter+0xf8/0x1c1
 [&lt;ffffffff8108a1a7>] ? shrink_zone+0x5f/0x9a
 [&lt;ffffffff8108b138>] ? do_try_to_free_pages+0x21e/0x4e4
 [&lt;ffffffff810830e2>] ? get_page_from_freelist+0x477/0x4a8
 [&lt;ffffffff8108b4e4>] ? try_to_free_pages+0x68/0x6a
 [&lt;ffffffff810837e9>] ? __alloc_pages_nodemask+0x4cf/0x75c
 [&lt;ffffffff81083af2>] ? __get_free_pages+0x12/0x41
 [&lt;ffffffffa0049839>] ? kv_alloc+0x28/0x40 [spl]
 [&lt;ffffffffa0049882>] ? spl_cache_grow_work+0x31/0x3bd [spl]
 [&lt;ffffffffa004c8ab>] ? taskq_thread+0x2be/0x447 [spl]
 [&lt;ffffffff81048cfb>] ? try_to_wake_up+0x219/0x219
 [&lt;ffffffffa004c5ed>] ? task_expire+0xf6/0xf6 [spl]
 [&lt;ffffffff8103e65a>] ? kthread+0x84/0x8c
 [&lt;ffffffff81310d54>] ? kernel_thread_helper+0x4/0x10
 [&lt;ffffffff8103e5d6>] ? kthread_freezable_should_stop+0x58/0x58
 [&lt;ffffffff81310d50>] ? gs_change+0xb/0xb

# echo l > /proc/sysrq-trigger
CPU0:
 ffff88042fc03ef0 ffff88042fc03f08 0000000000000046 ffff88042fc03f68
 0000000000000001 ffff8804179576a8 ffff88041795775c ffff88042fc03f38
 ffffffff8100473a ffff88042fc03f58 ffffffff811d584a ffffffff81310e4c
Call Trace:
 &lt;IRQ>  [&lt;ffffffff8100473a>] ? show_stack+0x17/0x19
 [&lt;ffffffff811d584a>] ? showacpu+0x48/0x5b
 [&lt;ffffffff81310e4c>] ? call_softirq+0x1c/0x30
 [&lt;ffffffff810598d4>] ? generic_smp_call_function_single_interrupt+0xc7/0xe9
 [&lt;ffffffff810187b2>] ? smp_call_function_single_interrupt+0x22/0x31
 [&lt;ffffffff81310927>] ? call_function_single_interrupt+0x67/0x70
 &lt;EOI>  [&lt;ffffffff810a7365>] ? PageHuge+0xb/0x28
 [&lt;ffffffff8109d9e3>] ? __page_check_address+0x24/0x13f
 [&lt;ffffffff8109defd>] ? page_referenced_one+0xb5/0x16f
 [&lt;ffffffff8109ee46>] ? page_referenced+0x155/0x2a6
 [&lt;ffffffff81088f62>] ? shrink_page_list+0x1ce/0x7e8
 [&lt;ffffffff8108817e>] ? update_isolated_counts+0x12a/0x139
 [&lt;ffffffff81089ac3>] ? shrink_inactive_list+0x2a8/0x42a
 [&lt;ffffffff8108a026>] ? shrink_mem_cgroup_zone+0x3e1/0x503
 [&lt;ffffffff810b6a7f>] ? mem_cgroup_iter+0xf8/0x1c1
 [&lt;ffffffff8108a1a7>] ? shrink_zone+0x5f/0x9a
 [&lt;ffffffff8108b138>] ? do_try_to_free_pages+0x21e/0x4e4
 [&lt;ffffffff810830e2>] ? get_page_from_freelist+0x477/0x4a8
 [&lt;ffffffff8108b4e4>] ? try_to_free_pages+0x68/0x6a
 [&lt;ffffffff810837e9>] ? __alloc_pages_nodemask+0x4cf/0x75c
 [&lt;ffffffff81083af2>] ? __get_free_pages+0x12/0x41
 [&lt;ffffffffa0049839>] ? kv_alloc+0x28/0x40 [spl]
 [&lt;ffffffffa0049882>] ? spl_cache_grow_work+0x31/0x3bd [spl]
 [&lt;ffffffffa004c8ab>] ? taskq_thread+0x2be/0x447 [spl]
 [&lt;ffffffff81048cfb>] ? try_to_wake_up+0x219/0x219
 [&lt;ffffffffa004c5ed>] ? task_expire+0xf6/0xf6 [spl]
 [&lt;ffffffff8103e65a>] ? kthread+0x84/0x8c
 [&lt;ffffffff81310d54>] ? kernel_thread_helper+0x4/0x10
 [&lt;ffffffff8103e5d6>] ? kthread_freezable_should_stop+0x58/0x58
 [&lt;ffffffff81310d50>] ? gs_change+0xb/0xb

# zpool status -v
# zpool iostat -v
                capacity     operations    bandwidth
pool         alloc   free   read  write   read  write
-----------  -----  -----  -----  -----  -----  -----
tank         5.79T  4.21T    580     24  11.1M   634K
  Array      5.79T  4.21T    580     24  11.1M   634K
cache            -      -      -      -      -      -
  SSD-part1  60.9G  50.3G    713      3  11.9M   157K
-----------  -----  -----  -----  -----  -----  -----
</pre>

ZFS is not a root filesystem, just the mount point where backups from other systems are saved. The big problem is when it gets really bad even the ext4-based half of the system will get wedged and I can't ssh in anymore. Existing ssh sessions may or may not die.

This is another case of running 30 simultaneous rsync processes. The most reliable way to unwedge this system is to kill all the rsync processes, presumably because this frees up memory. When it gets bad enough that I can't ssh in I kill the rsync processes from the other side of the backup, hoping this course of action will cause what little progress is being made will be stopped by rsync realizing it's not connected anymore. Surprisingly it seems to work, though not immediately.

Though the kernel is cgroup enabled I am not actually using them and the cgroup subsystems are not mounted.

Oprofile stats, though while it was running it got unwedged so there's "normal" activity in here as well:
<pre>CPU: Core 2, speed 2327.66 MHz (estimated)
Counted CPU_CLK_UNHALTED events (Clock cycles when not halted) with a unit mask of 0x00 (Unhalted core cycles) count 2000000
samples  %        app name                 symbol name
7995      8.7435  vmlinux                  __isolate_lru_page
7105      7.7702  zfs.ko                   arc_evict
6139      6.7138  vmlinux                  mem_cgroup_lru_del_list
5226      5.7153  vmlinux                  __page_check_address
4697      5.1368  zlib_deflate             /zlib_deflate
3764      4.1164  vmlinux                  putback_inactive_pages
3464      3.7883  vmlinux                  shrink_page_list
2652      2.9003  vmlinux                  mutex_unlock
2400      2.6247  vmlinux                  page_referenced
2025      2.2146  rsync                    /usr/bin/rsync
1813      1.9827  vmlinux                  mutex_lock
1763      1.9281  zfs.ko                   lzjb_decompress
1594      1.7432  vmlinux                  mutex_trylock
1353      1.4797  vmlinux                  isolate_lru_pages
1137      1.2435  vmlinux                  page_referenced_one
1124      1.2292  spl.ko                   spl_kmem_cache_alloc
998       1.0914  vmlinux                  page_waitqueue
971       1.0619  zcommon                  /zcommon
961       1.0510  vmlinux                  unlock_page
</pre>

**Comment by behlendorf** [comment]
Closing as stale.  The l2arc header issue is still legitimate and is being trackers on the zfs tracker.
