### ISSUE TITLE
z_rd_int/* processes use a lot of I/O

### ISSUE THREAD

**Issue by Eudgen** [zfsonlinux/spl#276]
I use xen domU Debian 6 with zfs 0.6.0 as backup storage.
z_rd_int/* processes use a lot of I/O when server is idle. This entails high LA and zombies.

top - 14:43:40 up 1 day,  2:25,  1 user,  load average: 70.52, 65.26, 58.57
Tasks: 454 total,   2 running, 413 sleeping,   0 stopped,  39 zombie
Cpu(s):  0.5%us,  1.6%sy,  0.0%ni, 48.9%id, 48.8%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   4112828k total,  2358824k used,  1754004k free,   104024k buffers
Swap:        0k total,        0k used,        0k free,   180044k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  474 root       0 -20     0    0    0 D    5  0.0  29:01.71 txg_sync
 5648 root      20   0 89900  22m 3464 S    4  0.6   1:40.99 perl
  263 root       0 -20     0    0    0 S    3  0.0  19:11.45 arc_adapt
10736 root      20   0 45552 3456  656 D    2  0.1   0:00.39 rsync
  371 root      39  19     0    0    0 R    1  0.0  13:13.30 z_rd_int/1
  373 root      39  19     0    0    0 S    1  0.0  13:14.18 z_rd_int/3
  370 root      39  19     0    0    0 S    1  0.0  12:38.26 z_rd_int/0
  372 root      39  19     0    0    0 S    1  0.0  13:12.22 z_rd_int/2
  377 root      39  19     0    0    0 S    1  0.0  16:21.30 z_wr_iss/3
10740 root      20   0 11136 1544  932 R    1  0.0   0:00.14 top
  363 root      39  19     0    0    0 S    0  0.0   1:20.87 z_rd_iss/1
  374 root      39  19     0    0    0 S    0  0.0  18:07.77 z_wr_iss/0
  375 root      39  19     0    0    0 S    0  0.0  16:18.81 z_wr_iss/1
  392 root      39  19     0    0    0 S    0  0.0   0:18.13 z_wr_int/9

iotop
   LA             USER   PID  S      RW       R       W  %WA              CMD
                           0      13.28   13.27    0.01   59    1/75 run/lock

73.86             root   372  S    3.51    3.51    0.00   16     (z_rd_int/2)
73.86             root   373  S    3.31    3.31    0.00   15     (z_rd_int/3)
73.86             root   370  S    3.25    3.25    0.00   15     (z_rd_int/0)
73.86             root   371  S    2.92    2.92    0.00   13     (z_rd_int/1)

zpool iostat 5
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
backups     1.60T  1.42T    375     81  3.08M  1.41M
backups     1.60T  1.42T    509     87  4.85M   973K
backups     1.60T  1.42T    512     99  5.04M  1.43M

What do these z_rd_int/*? How to change their performance?
I will provide any additional information if needed.

**Comment by behlendorf** [comment]
Closing as stale.

**Comment by Adel-Magebinary** [comment]
For any of you seeing this problem, your pool might be scrubbing for some reason. Check your cron job or something. 

When z_rd_int was really hight, I found the pool started scrubbing for some reason.


```
  pool: rpool
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
	attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
	using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: scrub in progress since Sun Dec  8 00:24:01 2019
	4.81T scanned at 1.30G/s, 1.93T issued at 535M/s, 8.13T total
	0B repaired, 23.70% done, 0 days 03:22:38 to go
config:

	NAME                                                  STATE     READ WRITE CKSUM
	rpool                                                 ONLINE       0     0     0
	  raidz2-0                                            ONLINE       0     0     0
	    ata-ST2000VN004-2E4164_Z521QD1P                   ONLINE       0     0     0
	    ata-ST2000VN004-2E4164_Z522NA39                   ONLINE       0     0     0
	    ata-ST2000VN004-2E4164_Z522NAE6                   ONLINE       0     0     0
	  raidz1-2                                            ONLINE       0     0     0
	    ata-ST1000LM048-2E7172_ZDE9PDDM                   ONLINE       1     0     0
	    ata-ST1000LM014-1EJ164_W7704X0Q                   ONLINE       0     0     0
	    ata-ST2000LM015-2E8174_WDZBZQS7                   ONLINE       0     0     0
	  raidz2-3                                            ONLINE       0     0     0
	    ata-ST1000LM010-9YH146_Z100QG9T                   ONLINE       0     0     0
	    ata-ST2000DM001-1ER164_Z4Z3E6GC                   ONLINE       0     0     0
	    ata-ST2000DL003-9VT166_5YD7ER9Q                   ONLINE       0     0     0
	    ata-Hitachi_HTS725050A9A360_110211PCJ400GLGTHM2J  ONLINE       0     0     0
	    ata-ST9500420AS_5VJ4CJEC                          ONLINE       0     0     0
	logs	
	  mirror-1                                            ONLINE       0     0     0
	    nvme-eui.0025385681b1c4fa-part4                   ONLINE       0     0     0
	    nvme-eui.0025385681b1c4fa-part5                   ONLINE       0     0     0
	cache
	  nvme0n1p2                                           ONLINE       0     0     0
	  nvme0n1p3                                           ONLINE       0     0     0

errors: No known data errors

```
