### ISSUE TITLE
DKMS build error on QubesOS R2 Beta 2 = missing binary operator before token "("

### ISSUE THREAD

**Issue by Nukama** [zfsonlinux/spl#284]
Tried to upgrade from 0.6.1 which worked without issues.

/var/lib/dkms/spl/0.6.2/build/make.log
<pre><code>
DKMS make.log for spl-0.6.2 for kernel 3.7.6-2.pvops.qubes.x86_64 (x86_64)
Tue Aug 27 18:44:25 UTC 2013
make  all-recursive
make[1]: Entering directory `/var/lib/dkms/spl/0.6.2/build'
Making all in include
make[2]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include'
Making all in fs
make[3]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include/fs'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include/fs'
Making all in linux
make[3]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include/linux'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include/linux'
Making all in rpc
make[3]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include/rpc'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include/rpc'
Making all in sharefs
make[3]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include/sharefs'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include/sharefs'
Making all in sys
make[3]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include/sys'
Making all in fm
make[4]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include/sys/fm'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include/sys/fm'
Making all in fs
make[4]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include/sys/fs'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include/sys/fs'
Making all in sysevent
make[4]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include/sys/sysevent'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include/sys/sysevent'
make[4]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include/sys'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include/sys'
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include/sys'
Making all in util
make[3]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include/util'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include/util'
Making all in vm
make[3]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include/vm'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include/vm'
make[3]: Entering directory `/var/lib/dkms/spl/0.6.2/build/include'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include'
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/include'
Making all in rpm
make[2]: Entering directory `/var/lib/dkms/spl/0.6.2/build/rpm'
Making all in fedora
make[3]: Entering directory `/var/lib/dkms/spl/0.6.2/build/rpm/fedora'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/rpm/fedora'
Making all in generic
make[3]: Entering directory `/var/lib/dkms/spl/0.6.2/build/rpm/generic'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/rpm/generic'
make[3]: Entering directory `/var/lib/dkms/spl/0.6.2/build/rpm'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/rpm'
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/rpm'
Making all in module
make[2]: Entering directory `/var/lib/dkms/spl/0.6.2/build/module'
make -C /lib/modules/3.7.6-2.pvops.qubes.x86_64/build SUBDIRS=`pwd`  CONFIG_SPL=m modules
make[3]: Entering directory `/usr/src/kernels/3.7.6-2.pvops.qubes.x86_64'
  CC [M]  /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-debug.o
  CC [M]  /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-proc.o
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-proc.c:41:69: error: missing binary operator before token "("
make[5]: *** [/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-proc.o] Error 1
make[4]: *** [/var/lib/dkms/spl/0.6.2/build/module/spl] Error 2
make[3]: *** [_module_/var/lib/dkms/spl/0.6.2/build/module] Error 2
make[3]: Leaving directory `/usr/src/kernels/3.7.6-2.pvops.qubes.x86_64'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/dkms/spl/0.6.2/build'
make: *** [all] Error 2
</code></pre>

**Comment by behlendorf** [comment]
This is believed to have been resolved.
