### ISSUE TITLE
Non-optimized BSWAP_32/64

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/spl#295]
The byte swap code in include/sys/byteorder.h is taken from an old version of Open Solaris. It has since been optimized:

https://blogs.oracle.com/DanX/entry/optimizing_byte_swapping_for_fun

GCC offers builtins that should translate into native machine instructions on Intel architectures, which should be even more efficient.

http://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html#Other-Builtins

We could use them when __GNUC__ is defined and fallback to generic routines otherwise (for compatibility with other compilers). Note that a comment on the blog post includes an even better byteswap routine.

I noticed this opportunity for optimization when working on the sgbuf patches and I am filing this issue so that I do not forget.

**Comment by rtvd** [comment]
I see that BSWAP macros are defined in two places:
* ZFS: lib/libspl/include/sys/byteorder.h
* SPL: include/sys/sysmacros.h

Doesn't ZFS use SPL headers anyway? Perhaps lib/libspl/include/sys/byteorder.h should just include include/sys/sysmacros.h in order to avoid the duplication?

**Comment by behlendorf** [comment]
@rtvd ZFS uses the libspl headers for user space builds and the spl headers in kernel space.  The BSWAP_* macros are used just by the ZFS code.

**Comment by rtvd** [comment]
There seem to be no easy way to use pshufb in GCC. And given that GCC can figure out that the relevant macros can be executed as bswap instructions it seems that modifying the code would only add unnecessary complexity.

**Comment by behlendorf** [comment]
Closing.  Based on the comments above gcc appears to already be correctly optimizing this.
