### ISSUE TITLE
Unable to build an empty module

### ISSUE THREAD

**Issue by Fullmetal8ender** [zfsonlinux/spl#318]
Hello!
I use Ubuntu 10.04. I trying to compile modules for kernel 3.8.0 from precize (12.04) repo. I have installed linux-image, linux-headers. When i run ./configure i got

checking spl config... all
checking kernel source directory... /usr/src/linux-headers-3.8.0-34-generic
checking kernel build directory... /usr/src/linux-headers-3.8.0-34-generic
checking kernel source version... 3.8.0-34-generic
checking kernel file name for module symbols... Module.symvers
checking whether debugging is enabled... no
checking whether basic debug logging is enabled... yes
checking whether basic kmem accounting is enabled... yes
checking whether detailed kmem tracking is enabled... no
checking whether modules can be built... no
configure: error: **\* Unable to build an empty module.

Can You tell me what this error means?

**Comment by kernelOfTruth** [comment]
Got this also with glibc 2.11 on Gentoo Linux, but the reason for the error message

was that ccache was enable,

upon disabling ccache - the compilation worked

**Comment by bhakimi** [comment]
<-- gentoo user, where do you disable ccache?

**Comment by kernelOfTruth** [comment]
/etc/portage/make.conf

under

```
FEATURES="-ccache -distcc"
```

or simply remove 

ccache and distcc from FEATURES
