### ISSUE TITLE
OpenSuSE/SuSE  rpmbuild  SPL 0.6.2 -  Bogus kmodtool usage   spl-kmod.spec.in

### ISSUE THREAD

**Issue by hvenzke** [zfsonlinux/spl#320]
Dear Brian,

If you whant to use your own kernel mod Tool  fine.
But  you must make shure the _realy_  use the correct path please to execute it.
The rpmmacro nowhere exist in SLES / OpenSuSE  / SuSE till _TODAY_

 /usr/src/packages/SOURCES are NONSTANDART  for binary scripts  shuold be 
 /usr/local/bin

------------------------- patch-----------------------------------------------------------------

<pre>
--- spl-kmod.spec.orig1 2013-12-21 18:11:15.036969353 +0000
+++ spl-kmod.spec       2013-12-21 18:28:58.250436076 +0000
@@ -74,10 +74,16 @@

 %prep
 # Error out if there was something wrong with kmodtool.
+if [ ! -f /usr/local/bin/kmodtool ]; then
+        cp -f %{SOURCE10} /usr/local/bin/kmodtool
+       chmod 755 /usr/local/bin/kmodtool
+       %define kmodtoolbin /usr/local/bin/kmodtool
+fi
+
 %{?kmodtool_check}

 # Print kmodtool output for debugging purposes:
-bash %{SOURCE10} --target %{_target_cpu} %{?repo:--repo %{?repo}}  --kmodname %{name} %{?buildforkernels:--%{buildforkernels}} --devel  %{?prefix:--prefix "%{?prefix}"} %{?kernels:--for-kernels "%{?kernels}"} %{?kernelbuildroot:--buildroot "%{?kernelbuildroot}"} 2>/dev/null
+bash %{kmodtoolbin} --target %{_target_cpu} %{?repo:--repo %{?repo}}  --kmodname %{name} %{?buildforkernels:--%{buildforkernels}} --devel  %{?prefix:--prefix "%{?prefix}"} %{?kernels:--for-kernels "%{?kernels}"} %{?kernelbuildroot:--buildroot "%{?kernelbuildroot}"} 2>/dev/null

 %if %{with debug}
     %define debug --enable-debug
</pre>

**Comment by behlendorf** [comment]
Closing as stale, this packaging issue I believe has been address by those SuSe zfs packagers.
