### ISSUE TITLE
SPL hangs when trying to import a damaged pool

### ISSUE THREAD

**Issue by petaramesh** [zfsonlinux/spl#329]
Hi,

I have a zpool which got damaged in an unknown way - system crash during resilvering - and now it will not import.

Trying to import it causes the following kernel messages to be logged : 

(This was obtained booting a live Ubuntu 13.10 AMD 64 USB key, then installing the latest native ZFS/SPL available from ppa:zfs-native/stable )

[    0.000000] Linux version 3.11.0-12-generic (buildd@allspice) (gcc version 4.8.1 (Ubuntu/Linaro 4.8.1-10ubuntu7) ) #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 (Ubuntu 3.11.0-12.19-generic 3.11.3)

[ 1182.784166] SPL: Loaded module v0.6.2-1~saucy
[ 1182.789255] znvpair: module license 'CDDL' taints kernel.
[ 1182.789274] Disabling lock debugging due to kernel taint
[ 1182.883113] ZFS: Loaded module v0.6.2-1~saucy, ZFS pool version 5000, ZFS filesystem version 5
[ 1184.455124] SPL: using hostid 0x007f0101

[ 2798.542251] zfs: freeing free segment (offset=42949672960 size=512)
[ 2798.542270] SPLError: 16038:0:(spl-err.c:48:vpanic()) SPL PANIC
[ 2798.542278] SPL: Showing stack for process 16038
[ 2798.542287] CPU: 0 PID: 16038 Comm: z_wr_iss/0 Tainted: PF          O 3.11.0-12-generic #19-Ubuntu
[ 2798.542291] Hardware name: System manufacturer System Product Name/M3N78-VM, BIOS 1406    10/30/2009
[ 2798.542296]  ffffffffa076ba68 ffff880088a018c8 ffffffff816e547a 0000000000000000
[ 2798.542304]  ffff880088a018d8 ffffffffa0614507 ffff880088a01900 ffffffffa06155a1
[ 2798.542312]  ffffffffa0628b91 000000000000000a 0000000000000003 ffff880088a01a18
[ 2798.542319] Call Trace:
[ 2798.542336]  [<ffffffff816e547a>] dump_stack+0x45/0x56
[ 2798.542370]  [<ffffffffa0614507>] spl_debug_dumpstack+0x27/0x40 [spl]
[ 2798.542386]  [<ffffffffa06155a1>] spl_debug_bug+0x81/0xe0 [spl]
[ 2798.542405]  [<ffffffffa06217c5>] vpanic+0x65/0x80 [spl]
[ 2798.542414]  [<ffffffff816e8902>] ? mutex_lock+0x12/0x2f
[ 2798.542422]  [<ffffffff816e8902>] ? mutex_lock+0x12/0x2f
[ 2798.542570]  [<ffffffffa074cb19>] ? zio_done+0x529/0xbd0 [zfs]
[ 2798.542579]  [<ffffffff816e8902>] ? mutex_lock+0x12/0x2f
[ 2798.542630]  [<ffffffffa06a8e5c>] ? remove_reference.isra.8+0x9c/0xb0 [zfs]
[ 2798.542651]  [<ffffffffa0621967>] vcmn_err+0x47/0x50 [spl]
[ 2798.542727]  [<ffffffffa0721509>] zfs_panic_recover+0x59/0x60 [zfs]
[ 2798.542802]  [<ffffffffa0703714>] space_map_remove+0x1c4/0x320 [zfs]
[ 2798.542877]  [<ffffffffa07033a2>] ? space_map_add+0x222/0x3d0 [zfs]
[ 2798.542935]  [<ffffffffa06bb9bf>] ? dmu_read+0x11f/0x190 [zfs]
[ 2798.543012]  [<ffffffffa0703edb>] space_map_load+0x19b/0x390 [zfs]
[ 2798.543084]  [<ffffffffa06eb5d6>] metaslab_activate+0xd6/0x150 [zfs]
[ 2798.543156]  [<ffffffffa06ecdb9>] metaslab_alloc+0x5d9/0xae0 [zfs]
[ 2798.543167]  [<ffffffff8104dee9>] ? default_spin_lock_flags+0x9/0x10
[ 2798.543177]  [<ffffffff8118de55>] ? __kmalloc+0x175/0x180
[ 2798.543194]  [<ffffffffa061b0e6>] ? kmem_alloc_debug+0x96/0x3c0 [spl]
[ 2798.543270]  [<ffffffffa074b05b>] zio_dva_allocate+0x8b/0x470 [zfs]
[ 2798.543346]  [<ffffffffa0747722>] ? zio_push_transform+0x42/0x90 [zfs]
[ 2798.543422]  [<ffffffffa0748da6>] zio_execute+0xa6/0x140 [zfs]
[ 2798.543441]  [<ffffffffa061e6e7>] taskq_thread+0x237/0x4b0 [spl]
[ 2798.543450]  [<ffffffff81091420>] ? finish_task_switch+0x50/0xf0
[ 2798.543459]  [<ffffffff81094950>] ? wake_up_state+0x20/0x20
[ 2798.543475]  [<ffffffffa061e4b0>] ? taskq_cancel_id+0x1f0/0x1f0 [spl]
[ 2798.543485]  [<ffffffff810847b0>] kthread+0xc0/0xd0
[ 2798.543492]  [<ffffffff810846f0>] ? kthread_create_on_node+0x120/0x120
[ 2798.543500]  [<ffffffff816f516c>] ret_from_fork+0x7c/0xb0
[ 2798.543507]  [<ffffffff810846f0>] ? kthread_create_on_node+0x120/0x120

**Comment by behlendorf** [comment]
Closing.  This issue belongs on the ZFS tracker and there is already an existing issue  there for improved handing of a corrupted space map.
