### ISSUE TITLE
Why is "CONFIG_KALLSYMS" required for a "in-tree builtin module building"?

### ISSUE THREAD

**Issue by peterbowey** [zfsonlinux/spl#338]
Please explain why a "in-tree builtin module build" requires "CONFIG_KALLSYMS"

Status on building "SPL" into my kernel tree is:
```
checking whether CONFIG_KALLSYMS is defined... no
configure: error:
        *** This kernel does not include the required kallsyms support.
        *** Rebuild the kernel with CONFIG_KALLSYMS=y set
```
There is a slight over-head in the kernel time and size to enable this "CONFIG_KALLSYMS=y" option. I do not know of other 'in-tree' modules that require this?

**Comment by behlendorf** [comment]
Closing, this check was removed by 44778f41100f88e7458d4deb2335ad09ce0bd0ea.  There no longer a CONFIG_KALLSYMS dependency.
