### ISSUE TITLE
Unknown symbol __fentry__

### ISSUE THREAD

**Issue by odoucet** [zfsonlinux/spl#354]
On Centos 6.5, adding spl/zfs with ZoL RPM provided.
On startup, the following error is encountered: 
```
spl: Unknown symbol __fentry__ (err 0)
```

Tried to cleanup and rebuild : 
```
dkms remove -m zfs -v 0.6.2 --all
dkms remove -m spl -v 0.6.2 --all
dkms add -m spl -v 0.6.2 
dkms add -m zfs -v 0.6.2 
dkms install -m spl -v 0.6.2 
dkms install -m zfs -v 0.6.2 
```
Leads to the same error.
When building, no error nor warning is printed.
Kernel is 3.10.37 from elrepo (3.10.37-1.el6.elrepo.x86_64)

**Comment by behlendorf** [comment]
Closing, more information is needed and this hasn't been reported again.
