### ISSUE TITLE
slabtop and /proc/spl/kmem/slab difference

### ISSUE THREAD

**Issue by antry** [zfsonlinux/spl#373]
slabtop show

 Active / Total Objects (% used)    : 4852012 / 4982054 (97.4%)
 Active / Total Slabs (% used)      : 54282 / 54282 (100.0%)
 Active / Total Caches (% used)     : 72 / 105 (68.6%)
 Active / Total Size (% used)       : 386092.82K / 401266.20K (96.2%)
 Minimum / Average / Maximum Object : 0.01K / 0.08K / 8.00K

arc_summary from /proc/spl/kmem/slab show
SPL Memory Usage:
  SPL slab allocated:         90,346 MB
  SPL slab used:              58,770 MB

how those counters coexists?

**Comment by kernelOfTruth** [comment]
@AndCycle sounds like that you're suffering from the problem that ARC doesn't reclaim/prune objects fast enough - please take a look at: https://github.com/zfsonlinux/zfs/pull/3181

**Comment by AndCycle** [comment]
@kernelOfTruth thanks for the reminder

**Comment by behlendorf** [comment]
Closing.  Many improvements have been made to improve the ARC behavior, if issues still remain let's open a issue on the zfs tracker.
