### ISSUE TITLE
spl-kmod build fails with two kernel-devel packages installed

### ISSUE THREAD

**Issue by LaHaine** [zfsonlinux/spl#385]
This is on Scientific Linux 6.5 (based on Red Hat Enterprise):
% rpmbuild --rebuild spl-kmod-0.6.3-1.el6.src.rpm
error: Package already exists: %package       -n kmod-spl-devel
% rpm -q kernel-devel
kernel-devel-2.6.32-431.29.2.el6.x86_64
kernel-devel-2.6.32-431.23.3.el6.x86_64

The build works fine if I remove one kernel-devel package. This was working fine with spl 0.6.1.

**Comment by alphacc** [comment]
I still have the problem with 0.6.4.2 ? Any hint on the solution ?

**Comment by behlendorf** [comment]
Closing.  Post spl/zfs merge there is no longer a kmod-spl-devel package to cause a conflict.
