### ISSUE TITLE
spl_kmem_cache_reclaim=0 causes splat to hang in linux:shrinker on 3.14.14-gentoo

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/spl#404]
c1aef26944ca8bc18e9f46f464c2957890c707e9 made spl_kmem_cache_reclaim=0 the default, but it causes splat to hang in linux:shrinker on 3.14.14-gentoo. I caught this in my local test VM when trying to refresh #369. I have confirmed that the current HEAD + pull request #403 still suffers from this problem.

**Comment by behlendorf** [comment]
Closing,  This fix was merged as 802a4a2ad53f6844ce2dbbf219a5e373ebd24688.
