### ISSUE TITLE
man spl-module-parameters.5 is missing some information on additional spl_kmem_cache_* settings

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/spl#405]
Hi,

FYI:

according to http://code.metager.de/source/xref/zfs/linux/spl/man/man5/spl-module-parameters.5 
& 
man spl-module-parameters

the following settings need information

```
/sys/module/spl/parameters/spl_kmem_cache_kmem_limit
/sys/module/spl/parameters/spl_kmem_cache_max_size
/sys/module/spl/parameters/spl_kmem_cache_obj_per_slab
/sys/module/spl/parameters/spl_kmem_cache_obj_per_slab_min
/sys/module/spl/parameters/spl_kmem_cache_slab_limit
/sys/module/spl/parameters/spl_kmem_cache_reclaim
```

I'm currently on a tuning-trip and thus looking through what setting does what in the most efficient way ;)

**Comment by behlendorf** [comment]
Closing, all spl module options are now documented in the man page.
