### ISSUE TITLE
SPL module doesn't load on grsec kernel CONFIG_GRKERNSEC_HIDESYM enabled

### ISSUE THREAD

**Issue by coredumb** [zfsonlinux/spl#406]
Hello,

With CONFIG_GRKERNSEC_HIDESYM=y, spl module doesn't load with unkown symbol error:

# modprobe spl
FATAL: Error inserting spl (/lib/modules/3.14.21-100.el6.x86_64/extra/spl/spl.ko): Unknown symbol in module, or unknown parameter (see dmesg)
# dmesg 
(...)
: Unknown symbol mcount (err 0)

**Comment by behlendorf** [comment]
Closing due to not enough information.  There may legitimately be an issue here we'll want to revisit in the future.
