### ISSUE TITLE
zfsonlinux_4_all.deb fails on clean Wheezy: lsb-release dependency

### ISSUE THREAD

**Issue by tomascreemers** [zfsonlinux/spl#430]
I did not have this issue with `zfsonlinux_3~wheezy_all.deb`.

```
root@debian:/# wget -nv -P /tmp http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_4_all.deb
2015-01-31 19:57:23 URL:http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_4_all.deb [2040076/2040076] -> "/tmp/zfsonlinux_4_all.deb" [1]
root@debian:/# dpkg -i /tmp/zfsonlinux_4_all.deb
Selecting previously unselected package zfsonlinux.
(Reading database ... 9892 files and directories currently installed.)
Unpacking zfsonlinux (from /tmp/zfsonlinux_4_all.deb) ...
dpkg: dependency problems prevent configuration of zfsonlinux:
 zfsonlinux depends on lsb-release; however:
  Package lsb-release is not installed.

dpkg: error processing zfsonlinux (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 zfsonlinux
root@debian:/# 
```

At this point, lsb-release is not yet part of the system. It should get pulled in with the immediately following command:
```
apt-get update && apt-get install linux-image-amd64 debian-zfs
```

Manually installing `lsb-release` before `dpkg -i zfsonlinux_4_all.deb` solves the issue. Is this now a required dependency of zfsonlinux_4_all.deb or is the package accidentally depending on it? Either the [HOWTO](https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Debian-GNU-Linux-to-a-Native-ZFS-Root-Filesystem) or the package should get an update.

**Comment by tomascreemers** [comment]
I just noticed I opened this issue on spl while it should probably be on pkg-zfs. I can't immediately find a way to move it.

**Comment by behlendorf** [comment]
Let's get @FransUrbo's take on this quick and then move it as appropriate.

**Comment by FransUrbo** [comment]
In all my tests, lsb-release had always been installed by default (both on Wheezy and Jessie)... It now require that, because this version detects both Wheezy and Jessie (so I don't have to maintain two almost identical packages).

The only way I can see (or at least the easiest) is to update the web page regarding this... So we should either move it to https://github.com/zfsonlinux/pkg-zfs (although I don't what good that would do) or https://github.com/zfsonlinux/zfsonlinux.github.com). In either case, it's not a 'spl' issue (so this one should be closed as 'not relevant')...

**Comment by tomascreemers** [comment]
I was able to reproduce this problem with zfsonlinux_5_all.deb and the instructions at [HOWTO install Debian GNU Linux to a Native ZFS Root Filesystem] (https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Debian-GNU-Linux-to-a-Native-ZFS-Root-Filesystem). I have taken the liberty of updating those instructions to include `apt-get install lsb-release` before `dpkg -i zfsonlinux_5_all.deb`, which fixes this issue. Thank you for your responses :-)

**Comment by FransUrbo** [comment]
Ah, doh! It needs to be a pre-depends, not a depends. I'll fix that right away.

**Comment by tomascreemers** [comment]
Using zfsonlinux_6_all.deb seems more correct: it does not start installing; it detects the missing dependency before starting and stops. Combined with the instruction to install lsb-release first, this should be OK. Thank you!

> root@debian:/# wget -nv -P /tmp http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_6_all.deb
> 2015-04-19 22:08:39 URL:http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_6_all.deb [2039658/2039658] -> "/tmp/zfsonlinux_6_all.deb" [1]
> root@debian:/# dpkg -i /tmp/zfsonlinux_6_all.deb
> Selecting previously unselected package zfsonlinux.
> dpkg: regarding /tmp/zfsonlinux_6_all.deb containing zfsonlinux, pre-dependency problem:
>  zfsonlinux pre-depends on lsb-release
>   lsb-release is not installed.
> 
> dpkg: error processing /tmp/zfsonlinux_6_all.deb (--install):
>  pre-dependency problem - not installing zfsonlinux
> Errors were encountered while processing:
>  /tmp/zfsonlinux_6_all.deb
> root@debian:/# aptitude -Ryq2 install lsb-release
> The following NEW packages will be installed:
>   libexpat1{a} lsb-release mime-support{a} python{a} python-minimal{a} python2.7{a} python2.7-minimal{a}
> 0 packages upgraded, 7 newly installed, 0 to remove and 15 not upgraded.
> Need to get 4,938 kB of archives. After unpacking 16.1 MB will be used.
> Can not write log, openpty() failed (/dev/pts not mounted?)
> Selecting previously unselected package libexpat1:amd64.
> (Reading database ... 9892 files and directories currently installed.)
> Unpacking libexpat1:amd64 (from .../libexpat1_2.1.0-1+deb7u1_amd64.deb) ...
> Selecting previously unselected package mime-support.
> Unpacking mime-support (from .../mime-support_3.52-1+deb7u1_all.deb) ...
> Selecting previously unselected package python2.7-minimal.
> Unpacking python2.7-minimal (from .../python2.7-minimal_2.7.3-6+deb7u2_amd64.deb) ...
> Selecting previously unselected package python2.7.
> Unpacking python2.7 (from .../python2.7_2.7.3-6+deb7u2_amd64.deb) ...
> Selecting previously unselected package python-minimal.
> Unpacking python-minimal (from .../python-minimal_2.7.3-4+deb7u1_all.deb) ...
> Selecting previously unselected package python.
> Unpacking python (from .../python_2.7.3-4+deb7u1_all.deb) ...
> Selecting previously unselected package lsb-release.
> Unpacking lsb-release (from .../lsb-release_4.1+Debian8+deb7u1_all.deb) ...
> Processing triggers for man-db ...
> Can not write log, openpty() failed (/dev/pts not mounted?)
> Setting up libexpat1:amd64 (2.1.0-1+deb7u1) ...
> Setting up mime-support (3.52-1+deb7u1) ...
> Setting up python2.7-minimal (2.7.3-6+deb7u2) ...
> Linking and byte-compiling packages for runtime python2.7...
> Setting up python2.7 (2.7.3-6+deb7u2) ...
> Setting up python-minimal (2.7.3-4+deb7u1) ...
> Setting up python (2.7.3-4+deb7u1) ...
> Setting up lsb-release (4.1+Debian8+deb7u1) ...
> root@debian:/# dpkg -i /tmp/zfsonlinux_6_all.deb
> (Reading database ... 10737 files and directories currently installed.)
> Unpacking zfsonlinux (from /tmp/zfsonlinux_6_all.deb) ...
> Setting up zfsonlinux (6) ...
> root@debian:/#

**Comment by FransUrbo** [comment]
@tomascreemers Can we consider the matter closed and fixed with this new version of zfsonlinux? If so, would you mind closing the issue?

**Comment by tomascreemers** [comment]
Thank you for your time and effort :-)
