### ISSUE TITLE
mutex unlock serialization is implicit when CONFIG_MUTEX_SPIN_ON_OWNER=n

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/spl#431]
The workaround in a3c1eb77721a0d511b4fe7111bb2314686570c4b is only necessary when `CONFIG_MUTEX_SPIN_ON_OWNER` is active on a kernel. When it is not active, we add atomic instruction overhead for no reason. We could rewrite the code to only add the spinlocks when `CONFIG_MUTEX_SPIN_ON_OWNER` is active.

**Comment by ryao** [comment]
This isn't the case upon double checking the code.

**Comment by behlendorf** [comment]
Right, that said the a3c1eb7 fix probably isn't required for debug kernels with CONFIG_DEBUG_MUTEXES set.  However, I'd still recommend we always run with this fix.
