### ISSUE TITLE
Slow creation of dataset

### ISSUE THREAD

**Issue by michalstab** [zfsonlinux/spl#432]
Time to create dataset is longer with every new dataset. Tested on:
package zfs-0.6.3-1.2.el6.x86_64 (CentOS release 6.6 `2.6.32-504.8.1.el6.x86_64`)  
package zfs-0.6.3-1.2.el7.centos.x86_64 (CentOS release 7-0.1406 `3.10.0-123.13.2.el7.x86_64`)

With 7278 datasets 
```
[root@localhost ~]# time zfs create pool1/home2/aaas2
real	0m23.651s
user	0m19.804s
sys	0m3.567s
```

With 7280 datasets 
```
[root@localhost ~]# time zfs create pool1/home2/aaaps2
real	0m24.234s
user	0m20.013s
sys	0m4.005s
```

On FreeBSD works correctly.

**Comment by behlendorf** [comment]
Migrated to zfsonlinux/zfs#3105.
