### ISSUE TITLE
centos7.1 install 259_g0f7d2a4 fail

### ISSUE THREAD

**Issue by malexandvsc** [zfsonlinux/spl#445]
update to 259_g0f7d2a4 from 0.6.3-245_gbc88866 fails with warnings from spl-dkms, depmod which coincides with going from centos 7 to 7.1.1503 - release Kernel 3.10.0-123 to -229. 

Cleaning out dkms and remaining spl/zfs kernel modules did not resolve. 
 
For the sake of trying: installing 0.6.3-current after it fails as well.

**Comment by millerdc** [comment]
I'm seeing the same issue after updating from CentOS 7 to CentOS 7.1.

**Comment by malexandvsc** [comment]
well that's the resolution for the issue as initially filed:

first still got the same with the 0.6.4 release build - lacking at least some unicode etc. functions

depmod: ERROR: fstatat(4, splat.ko): No such file or directory
depmod: ERROR: fstatat(4, zavl.ko): No such file or directory
depmod: ERROR: fstatat(4, zunicode.ko): No such file or directory
[ 1559.142801] Disabling lock debugging due to kernel taint
[ 1559.147963] zfs: Unknown symbol u8_textprep_str (err 0)
[ 1559.148487] zfs: Unknown symbol u8_strcmp (err 0)
...

Turns out dmks spit some messages about the last centos 7.0 kernel (3.10.0-123.20.1.el7) despite being on 3.10.0-229.1.2, so the resolution was to remove prior kernels, clean out yum, dkms and prior zfs/dkms in /lib/modules and install 0.6.4 as packages.

**Comment by behlendorf** [comment]
Closing.
