### ISSUE TITLE
blk_unplug delay - high latency

### ISSUE THREAD

**Issue by hhhappe** [zfsonlinux/spl#452]
OS: CentOS 6.6
ZFS: 0.6.4.1
SPL: 0.6.4.1

I found the latency of an ioping test to be higher than expected. This is a ZFS fs on one SSD disk:

ioping -WWW /zfs/file
4.0 KiB from /zfs/file (zfs zfs): request=1 time=2.4 ms
4.0 KiB from /zfs/file (zfs zfs): request=2 time=2.8 ms
4.0 KiB from /zfs/file (zfs zfs): request=3 time=2.9 ms

ioping directly to the device or on top of ext4 gives the expected ~100us latency.

I've investigated with btrace and found that blk_unplug is not triggered, until timeout:

8,112 0 167 4.009409364 6309 A W 41472 + 32 <- (8,113) 39424
8,112 0 168 4.009410451 6309 Q W 41472 + 32 [z_wr_iss/5]
8,112 0 169 4.009411984 6309 G W 41472 + 32 [z_wr_iss/5]
8,112 0 170 4.009413594 6309 P N [z_wr_iss/5]
8,112 0 171 4.009414297 6309 I W 41472 + 32 [z_wr_iss/5]
8,112 0 172 4.011926785 0 UT N [swapper] 1
8,112 0 173 4.011931787 106 U N [kblockd/0] 1
8,112 0 174 4.011932297 106 D W 41472 + 32 [kblockd/0]
8,112 0 175 4.012571581 0 C W 41472 + 32 [0]

This is output from ext4. Scheduler also noop:

8,80 0 9 2.000339950 6488 Q WS 274432 + 8 [ioping]
8,80 0 10 2.000340643 6488 G WS 274432 + 8 [ioping]
8,80 0 11 2.000341204 6488 P N [ioping]
8,80 0 12 2.000341473 6488 I WS 274432 + 8 [ioping]
8,80 0 13 2.000342552 6488 U N [ioping] 1
8,80 0 14 2.000342991 6488 D WS 274432 + 8 [ioping]
8,80 0 15 2.000403533 0 C WS 274432 + 8 [0]

Then I tried ZFS on top of an ext4 file, then I get ~300us. Not as good but close enough given the extra layer.

I'm far from an expert on blkdev queuing, but my understanding is that it should be unplugged if something is waiting for it.

OBSERVATION: If you give ioping a ZFS dir instead of a file it will create a file for the testing. However, it will unlink the file right after it has opened it. This makes ZFS disable sync to disk, which makes sense because it will not be available in case of a crash.

I'm just wondering if it is intentional and up to standards. One might argue that data could be found with a bit of forensics.

**Comment by behlendorf** [comment]
You had it right the first time, I've reopened the ZFS issue.  I'll follow up there https://github.com/zfsonlinux/zfs/issues/3398
