### ISSUE TITLE
SPL 0.6.5 Oopses with "Bug: Unable to handle kernel NULL pointer dereference"

### ISSUE THREAD

**Issue by wuffleton** [zfsonlinux/spl#475]
Hello. I've recently upgraded to ZFS/SPL 0.6.5 on Arch Linux, and have been getting random crashes that spit out kernel oops messages. I've been using the packages in our AUR maintainer's repo, but compiling them myself made no difference to stability. I've also tried the LTS kernel and ZFS/SPL packages to no avail. 

Upon causing the kernel oops, my system seems to be left in a frozen and partially working state (likely due to unpredictable ZFS behavior after SPL crashes). Any sort of SSH or TTY is a no-go, and most services crash, but occasionally I've seen Nginx still running and serving static content from my website. Other functions of the kernel seem to still be alive, since it doesn't freeze hard enough to trigger the watchdog for my server's automatic reset feature. 

I haven't found a way to reliably reproduce this issue, but if there's any other information that I can gather to help this issue along. Let me know. If you need more output from the oops, since I could probably set up a machine to watch from a serial console.

Package Versions: 
- zfs-git 0.6.5_r0_g7a27ad0_4.1.6_1-1
- spl-git 0.6.5_r0_gf17d005_4.1.6_1-1
- linux 4.1.6-1

Screenshot of the oops:
![zfs1](https://cloud.githubusercontent.com/assets/4283099/9952204/5baa225c-5d87-11e5-965d-e57a9f803223.png)

**Comment by behlendorf** [comment]
Is this still an issue with the latest point release, 0.6.5.6.

**Comment by rtvd** [comment]
There is only a few places where NULL pointer dereference could happen in taskq_thread.
Is there a way to add assertions to that function? In Linux code I would have added BUG_ON but that is surely not portable.

**Comment by behlendorf** [comment]
@rtvd you can use the VERIFY*() macros for this.  They behave like ASSERT*() but cannot be compiled out.

**Comment by behlendorf** [comment]
Closing.  ArchLinux has moved on to the 0.7.x series and I've seen no other reports of this.  Open a new issue on the zfs tracker if this is observed again.
