### ISSUE TITLE
spl-dkms does not remove old modules on upgrade/uninstall

### ISSUE THREAD

**Issue by utopiabound** [zfsonlinux/spl#476]
spl-dkms checks for `/var/lib/dkms/spl/0.6.5.1/build/spl.release` which doesn't exist.  dkms removes  `/var/lib/dkms/spl/0.6.5.1/build` after install (or at least  `/var/lib/dkms/spl/0.6.5.1/build/*` depending on the dkms version).

This missing file prevents dkms from removing itself in the uninstall script, and thus leaving behind cruft when the upgrade comes through.

**Comment by FransUrbo** [comment]
What distribution is this and how/where did you get your packages from?

**Comment by behlendorf** [comment]
@utopiabound I've definitely seen something very much like this but I thought we addressed it.  I guess not.  Can you propose a fix?

**Comment by utopiabound** [comment]
spl-dkms should just do a "dkms remove" in %post.

**Comment by behlendorf** [comment]
Merged to the zfs-0.6.5-release branch but not master.  We're going to need to do something slightly different on master to keep updates working on the testing repository.
