### ISSUE TITLE
Kernel builtins broken in 0.6.5.2?

### ISSUE THREAD

**Issue by gcs-github** [zfsonlinux/spl#481]
Hello!

I stumbled upon an oddity today patching my kernel with SPL/ZFS 0.6.5.2.

Using `./copy-builtin` on a configured kernel tree works normally, and I'm then able to compile my kernel with SPL and then ZFS built-in without a hitch.

But, if after the `./copy-builtin` succeeds I issue a "make clean" or a "make distclean" in my kernel tree so I can distribute the patched kernel source or create different kernel configurations, in any subsequent kernel build attempt, SPL will fail to compile during the regular kernel build process, with the following message:

```
make[2]: *** No rule to make target 'spl/spl/spl-proc.o', needed by 'spl/spl/spl.o'.  Stop.
scripts/Makefile.build:403: recipe for target 'spl/spl' failed
make[1]: *** [spl/spl] Error 2
Makefile:949: recipe for target 'spl' failed
make: *** [spl] Error 2
```

This is with a vanilla Linux 4.2.3 source tree.

Linux kernel's "make clean" deleting more than it should, maybe?

**Comment by behlendorf** [comment]
It certainly looks that way.  Thanks for filing this, we'll look in to it time permitting.

**Comment by berney** [comment]
I had the same symptoms. In the Makefiles was a src= and obj= lines pointing to portage tmp dirs. I commented them out and then make would work.

**Comment by behlendorf** [comment]
Merged:

4e6f996 Fix --enable-linux-builtin
