### ISSUE TITLE
Ubuntu 15.10 - 4.2.0-17-generic module build fails

### ISSUE THREAD

**Issue by mrBulb** [zfsonlinux/spl#495]
Hey received the following message when updated the kernel from 4.2.0-16-generic 4.2.0-17-generic via apt-get:

    Running depmod.
    update-initramfs: deferring update (hook will be called later)
    Examining /etc/kernel/postinst.d.
    run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.2.0-17-generic /boot/vmlinuz-4.2.0-17-generic
    run-parts: executing /etc/kernel/postinst.d/dkms 4.2.0-17-generic /boot/vmlinuz-4.2.0-17-generic
    configure: error:
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.
    Error! Bad return status for module build on kernel: 4.2.0-17-generic (x86_64)
    Consult /var/lib/dkms/zfs/0.6.5.3/build/make.log for more information.

The make log:

    DKMS make.log for zfs-0.6.5.3 for kernel 4.2.0-17-generic (x86_64)
    Fr 6. Nov 09:29:45 CET 2015
    make  all-recursive
    make[1]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build'
    Making all in include
    make[2]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build/include'
    Making all in linux
    make[3]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build/include/linux'
    make[3]: Nothing to be done for 'all'.
    make[3]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build/include/linux'
    Making all in sys
    make[3]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys'
    Making all in fm
    make[4]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys/fm'
    Making all in fs
    make[5]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys/fm/fs'
    make[5]: Nothing to be done for 'all'.
    make[5]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys/fm/fs'
    make[5]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys/fm'
    make[5]: Nothing to be done for 'all-am'.
    make[5]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys/fm'
    make[4]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys/fm'
    Making all in fs
    make[4]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys/fs'
    make[4]: Nothing to be done for 'all'.
    make[4]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys/fs'
    make[4]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys'
    make[4]: Nothing to be done for 'all-am'.
    make[4]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys'
    make[3]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build/include/sys'
    make[3]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build/include'
    make[3]: Nothing to be done for 'all-am'.
    make[3]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build/include'
    make[2]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build/include'
    Making all in rpm
    make[2]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build/rpm'
    #
    make[2]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build/rpm'
    Making all in module
    make[2]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build/module'
    make -C /lib/modules/4.2.0-17-generic/build SUBDIRS=`pwd`  CONFIG_ZFS=m modules
    make[3]: Entering directory '/usr/src/linux-headers-4.2.0-17-generic'
      CC [M]  /var/lib/dkms/zfs/0.6.5.3/build/module/avl/avl.o
    /var/lib/dkms/zfs/0.6.5.3/build/module/avl/avl.c: In function ‘avl_add’:
    /var/lib/dkms/zfs/0.6.5.3/build/module/avl/avl.c:647:2: warning: ‘where’ may be used uninitialized in this function [-Wmaybe-uninitialized]
      avl_insert(tree, new_node, where);
      ^
      LD [M]  /var/lib/dkms/zfs/0.6.5.3/build/module/avl/zavl.o
      CC [M]  /var/lib/dkms/zfs/0.6.5.3/build/module/nvpair/nvpair.o
      ... A bunch ob objects
    
      Building modules, stage 2.
      MODPOST 6 modules
      CC      /var/lib/dkms/zfs/0.6.5.3/build/module/avl/zavl.mod.o
      LD [M]  /var/lib/dkms/zfs/0.6.5.3/build/module/avl/zavl.ko
      CC      /var/lib/dkms/zfs/0.6.5.3/build/module/nvpair/znvpair.mod.o
      LD [M]  /var/lib/dkms/zfs/0.6.5.3/build/module/nvpair/znvpair.ko
      CC      /var/lib/dkms/zfs/0.6.5.3/build/module/unicode/zunicode.mod.o
      LD [M]  /var/lib/dkms/zfs/0.6.5.3/build/module/unicode/zunicode.ko
      CC      /var/lib/dkms/zfs/0.6.5.3/build/module/zcommon/zcommon.mod.o
      LD [M]  /var/lib/dkms/zfs/0.6.5.3/build/module/zcommon/zcommon.ko
      CC      /var/lib/dkms/zfs/0.6.5.3/build/module/zfs/zfs.mod.o
      LD [M]  /var/lib/dkms/zfs/0.6.5.3/build/module/zfs/zfs.ko
      CC      /var/lib/dkms/zfs/0.6.5.3/build/module/zpios/zpios.mod.o
      LD [M]  /var/lib/dkms/zfs/0.6.5.3/build/module/zpios/zpios.ko
    make[3]: Leaving directory '/usr/src/linux-headers-4.2.0-17-generic'
    make[2]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build/module'
    make[2]: Entering directory '/var/lib/dkms/zfs/0.6.5.3/build'
    make[2]: Nothing to be done for 'all-am'.
    make[2]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build'
    make[1]: Leaving directory '/var/lib/dkms/zfs/0.6.5.3/build'

I'm not quite sure if it really fails or if just the compile-warning leads to a non 0 return code.

**Comment by Amitie10g** [comment]
Several users reported errors with ``spl 0.6.5.3``., and the SPL build issue are caused mainle due the zfs and spl version does not match (at least in my cases).

* Before anythink, **make snapshots** and keep old initrds!!! An old initrd with zfs and spl built is enough to the system to boot.
* Try to downgrade zfs and spl to 0.6.5.2
* Be sure to update the both ``zfs`` and ``spl`` related packages to the **exact** same version (0.6.5.3). If no package available (in the case of Debian), **don't** update, unless you're testing and taken all the precautions against disasters.

**Comment by FransUrbo** [comment]
Please move (open a new and close this) this to the correct repo: https://github.com/zfsonlinux/pkg-zfs

**Comment by mrBulb** [comment]
Moved to https://github.com/zfsonlinux/pkg-zfs/issues/183
