### ISSUE TITLE
zfs/spl 0.6.5.3 build fails for linux-4.3 when configured as built-in modules

### ISSUE THREAD

**Issue by gedia** [zfsonlinux/spl#498]
It seems that building a 4.3 kernel with spl and zfs-kmod built-in fails. They build fine as modules. Linux-4.2.3 is not affected by this. I'm attaching a build log here as well as my kernel configuration.

GCC version is: gcc (Gentoo 5.2.0 p1.1, pie-0.6.4) 5.2.0
[build-log.txt](https://github.com/zfsonlinux/spl/files/32247/build-log.txt)
[config.txt](https://github.com/zfsonlinux/spl/files/32248/config.txt)

**Comment by behlendorf** [comment]
Just taking a quick look it's not clear to me that it built any of the spl.  Since the errors are all about missing spl symbols that would make sense.

**Comment by hunbalazs** [comment]
@behlendorf it didnt, it seems that (for some reason) it only builds ZFS but not SPL
```
# grep CONFIG_SPL .config
CONFIG_SPLIT_PTLOCK_CPUS=4
CONFIG_SPL=y
```
it works with kernel 4.2.6
(gcc version 4.9.3 (Gentoo 4.9.3 p1.1, pie-0.6.2))

**Comment by sergiall** [comment]
It works with kernel 4.2.6 (gcc version 5.2.1 Debian stretch/sid,Ubuntu 15.10/16.04.
Both SPL & ZFS build ok and work fine,but for linux 4.3 it still fail for build :( .

**Comment by behlendorf** [comment]
@sergiall @hunbalazs I've proposed two patches to fix this.  Any additional testing would be appreciated, I've verified the fix with v4.4-rc3 but it should fix all kernels.

**Comment by hunbalazs** [comment]
Kernel built and running.
Thank you very much @behlendorf .

**Comment by behlendorf** [comment]
@hunbalazs thanks, this has been merged to master and will appear in the next point release.

4e6f996 Fix --enable-linux-builtin

**Comment by sergiall** [comment]
Wow! Thank you very much @behlendorf !
