### ISSUE TITLE
Outdated dkms package in the Zol Ubuntu repo used instead of official

### ISSUE THREAD

**Issue by L-B** [zfsonlinux/spl#511]
The Ubuntu repo contains this version of the dkms package:
2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty

The latest available is:
2.2.0.3-1.1ubuntu5.14.04.5

Since the ZoL version is pinned, it's used instead of the latest, and lacks in particular a fix needed for an API break, described there:
https://bugs.launchpad.net/ubuntu/+source/dkms/+bug/1499842

An upgrade is needed.

**Comment by behlendorf** [comment]
Closing.  The official zfs ubuntu packages are now maintained by Canonical and dkms is no longer needed.

**Comment by porbas** [comment]
Yes, Canonical maintains packages for ubuntu 16.04 - just released LTS. What about previous 14.04 LTS? It is going to be supported to April 2019.

**Comment by behlendorf** [comment]
@porbas the packages for 14.04 will still be available through the launchpad.  Since they're dkms based they should contain to build against the latest LTS kernels.  As for new updates that's up to @dajhorn.

**Comment by dajhorn** [comment]
@porbas,

This issue could be zfsonlinux/pkg-zfs#195.  Either way, DKMS in the PPA is usually upgraded with ZoL point releases, short of any production breakage.

Past that, note that you can safety edit the pin file, and that apport dumps for Precise and Trusty involving ZoL are, technically, tainted.

**Comment by dajhorn** [comment]
FYI,

Trusty is getting a full dkms backport from Xenial in its next SRU, which will obsolete dkms in the PPA.  I will, however, copy the final build into the PPA whenever it becomes available prior to the downstream point release.
