### ISSUE TITLE
lock with spl_kmem_cache using fio 

### ISSUE THREAD

**Issue by jimsalterjrs** [zfsonlinux/spl#522]
Using fio in ioengine=sync mode locks up ZFS permanently until hard reboot every time with the following configuration:

~~~~
[global]
bs=4K
ioengine=sync
size=32m

[write]
rw=randwrite

[read]
rw=randread
~~~~

This is on Ubuntu 14.04 with Wily kernel, fully patched and up to date, system just installed today.  Zpool is one mirror vdev of two WD Black 1TB drives.  Running fio with that config immediately locks up the system permanently until hard reboot with zero IO showing on iotop; top shows fio with 40% or so CPU and four spl_kmem_cache processes each with 20% or so.

Changing the ioengine to libaio makes everything work as expected.

**Comment by kernelOfTruth** [comment]
is 

```ioengine=psync```

and

```ioengine=vsync```

working ?


--------------------------------------------------
--------------------------------------------------

references:
http://linux.die.net/man/1/fio
http://www.thegeekstuff.com/2012/07/c-file-handling/

--------------------------------------------------

```
ioengine=str
Defines how the job issues I/O. The following types are defined:
sync

Basic read(2) or write(2) I/O. fseek(2) is used to position the I/O location.
```

**Comment by jimsalterjrs** [comment]
psync: works as expected
vsync: works as expected

**Comment by jimsalterjrs** [comment]
Actually I just hit the bug again with ioengine=libaio.  The difference: I killed the pool and created a new one with the same disks, this time as a pool of two single disks.  (I'm doing test runs of various topologies.)

**Comment by jimsalterjrs** [comment]
I'm hitting the bug now just doing pv < /dev/zero > test.bin on a zpool created from a single one of my WD 1TB disks. =\

I wonder if this has something to do with the Wily kernel.  I just recently started using the linux-generic-lts-wily kernel on 14.04 LTS machines, including this one.  I have not seen anything like this on any of my other (several tens of) zfs-on-ubuntu machines.

**Comment by kernelOfTruth** [comment]
According to https://wiki.ubuntu.com/WilyWerewolf/ReleaseNotes

Wily kernel means 4.2.y ?

**Comment by jimsalterjrs** [comment]
Correct.  4.2.2.

I'm installing the Vivid kernel (3.19) and going to try again there.  Interestingly, ZFS failed to build for 3.19 and griped about spl-dev.  I installed spl-dev, and now ZFS is rebuilding for 4.2 and for 3.19.  We'll see how it goes after the rebuild and booting into 3.19.

**Comment by jimsalterjrs** [comment]
Well, it's not the kernel.  I tried the same test - fio using ioengine=libaio and one 4K random reader and one 4K random writer, against a single-disk zpool - and got an immediate lockup using the 3.19 kernel also.

**Comment by jimsalterjrs** [comment]
Possibly related?  I watched the boot process after the last lockup and caught the following messages flashing across the console, which were also in `dmesg` when I checked:

~~~~
[   13.958017] vmap allocation for size 1089536 failed: use vmalloc=<size> to increase size.
[   13.967689] vmap allocation for size 1089536 failed: use vmalloc=<size> to increase size.
[   13.977830] vmap allocation for size 1089536 failed: use vmalloc=<size> to increase size.
[   13.988549] vmap allocation for size 1089536 failed: use vmalloc=<size> to increase size.
[   13.999245] vmap allocation for size 1089536 failed: use vmalloc=<size> to increase size.
[   14.010236] vmap allocation for size 1089536 failed: use vmalloc=<size> to increase size.
[   14.021422] vmap allocation for size 1089536 failed: use vmalloc=<size> to increase size.
[   14.033075] vmap allocation for size 1089536 failed: use vmalloc=<size> to increase size.
[   14.044666] vmap allocation for size 1089536 failed: use vmalloc=<size> to increase size.
[   14.056738] vmap allocation for size 1089536 failed: use vmalloc=<size> to increase size.
~~~~

**Comment by jimsalterjrs** [comment]
I thought the vmap messages might have had to do with me manually limiting the ARC to 128MB in /etc/modprobe.d/zfs.conf.  So I commented that out and restarted.  The vmap errors above did not reappear, but the system still locks up instantly when I run `fio`.

**Comment by kernelOfTruth** [comment]
Sure, if it impairs the function of any drivers ...

https://www.mythtv.org/wiki/Common_Problem:_vmalloc_too_small


Of what version are the zfs, spl, etc. kernel modules ?

How much RAM has that system ? swap ?

Is is a "native" system or a VM ?

output of 

``` /proc/meminfo ```

``` /proc/spl/kstat/zfs/arcstats ```

``` /proc/sys/vm/min_free_kbytes ```

``` /proc/sys/vm/mmap_min_addr ```

please

**Comment by kernelOfTruth** [comment]
referencing:

https://github.com/zfsonlinux/spl/issues/234 spl_kmem_cache high CPU usage
https://github.com/zfsonlinux/spl/issues/271 spl_kmem_cache spinning in shrink_mem_cgroup_zone
https://github.com/zfsonlinux/spl/issues/305 Kernel hang spl_kmem_cache/:308 on Ubuntu 13.10 kernel 3.11.0-12-generic
https://github.com/zfsonlinux/spl/issues/223 Poor benchmark performance

**Comment by jimsalterjrs** [comment]
oh, hell, THAT's why everything's behaving differently here... this is an x86 Ubuntu install.  Hadn't realized it was installed x86.  How much you want to bet all of this goes away if I reload it x86_64?

**Comment by kernelOfTruth** [comment]
Haha - just had a quick thought to ask whether this is a 32bit system prior to writing the last comment but figured that it couldn't be ;)

Well, it might go away with x86_64 but it's still important to know of this kind of behavior,

since it can also appear on other architectures (arm, ppc, ...)

**Comment by jimsalterjrs** [comment]
Well... gotta be honest, I've got work to do, and I'm kinda over x86 stuff.  I'm using an install on a pendrive that I did x86 originally so that it would boot on anything including old first-gen Atom embedded crap, but at this point, I'm inclined to just tell people "you have to replace that thing" if I encounter any more x86.

I'm going to reload with x86_64 and let you know how it goes.  I expect it'll make my problems go away, but I'll comment back here to let you know either way.

**Comment by jimsalterjrs** [comment]
confirmed - reloaded x86_64, same test is now behaving as normal.

Will test with ioengine=sync as well in a second, but I expect that will work fine as well - I've run fio against ZFS quite a lot in the last week or two and never encountered these problems until I accidentally started using x86.

**Comment by behlendorf** [comment]
@jimsalterjrs just for posterity what version of ZFS were you using.  There were several 32-bit fixes made recently but it's not clear if they would be sufficient to prevent the issue you were seeing.

**Comment by jimsalterjrs** [comment]
Fresh download from the zfs-native/stable PPA.  8~trusty 0.

BTW, two full days of exhaustive benchmarking later, yes, amd64 build is just fine.  It was just the i386 build that was (very!) wonky.
