### ISSUE TITLE
copy-builtin cannot be run more than once against the same target tree

### ISSUE THREAD

**Issue by infowolfe** [zfsonlinux/spl#526]
line 119 of copy-builtin:
```sed -i 's#+= kernel/#+= kernel/ spl/#' "$KERNEL_DIR/Makefile"```
results in line 887 of /usr/src/linux/Makefile:
```core-y      += kernel/ spl/ spl/ mm/ fs/ ipc/ security/ crypto/ block/```
upon make:
```Makefile:946: target 'spl' given more than once in the same rule````

something like
```grep 'kernel/ spl/' "$KERNEL_DIR/Makefile" || sed -i 's#+= kernel/#+= kernel/ spl/#' "$KERNEL_DIR/Makefile"```
is completely inelegant, but would fix this.

**Comment by behlendorf** [comment]
Good point, I'm a little surprised this hasn't come up until now.  Your fix looks reasonable to me and is similar to what `add_after()` does.  It's not elegant, but it's definitely functional.  Could you please open a pull request with your proposed fix so we can get it tested and reviewed.

**Comment by infowolfe** [comment]
Is there some reason why we're not just using `add_after()` in this case?

**Comment by behlendorf** [comment]
Yes, because we need to modify an existing line and not insert a new one.

**Comment by infowolfe** [comment]
Hence the why the PR makes the sed less fragile instead of replacing it with add_after.

**Comment by behlendorf** [comment]
I must have misunderstood your [previous comment](https://github.com/zfsonlinux/spl/issues/526#issuecomment-174735950), yes the fix looks good.

**Comment by simonvanderveldt** [comment]
Wouldn't it be cleaner to add spl to `core-y` on a separate line, that way you could check if the line you've added exists and that's it. Now you have to check a line that already exists and you have no control over.

Expected result:
```
core-y		+= kernel/ mm/ fs/ ipc/ security/ crypto/ block/ <whatever upstream adds>
core-y		+= spl/
```

**Comment by behlendorf** [comment]
@simonvanderveldt that would be cleaner but there's a dependency issue.  The `spl` directory must be built before the `fs` directory but after `kernel` and `mm`.

**Comment by simonvanderveldt** [comment]
@behlendorf ah, didn't know that, that's annoying/unfortunate. Not much we can do about it then.
