### ISSUE TITLE
"zpool status -v" shows tank/root/gentoo:<0x113c25> (no snapshots)

### ISSUE THREAD

**Issue by djdunn** [zfsonlinux/spl#539]
Before the scrub was over those enteries all related to one merge operation and reemerging them which unlinked those damaged files caused those enteries to show up.  I rememerged that package during the 2nd scrub

pool: tank
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub in progress since Tue Apr  5 09:39:02 2016
	4.99G scanned out of 739G at 55.0M/s, 3h47m to go
	0 repaired, 0.68% done
config:

	NAME        STATE     READ WRITE CKSUM
	tank        ONLINE       0     0    22
	  mirror-0  ONLINE       0     0     0
	    sdb     ONLINE       0     0     0
	    sda     ONLINE       0     0     0
	  mirror-1  ONLINE       0     0    44
	    sdc     ONLINE       0     0    44
	    sdd     ONLINE       0     0    44

errors: Permanent errors have been detected in the following files:

        tank/root/gentoo:<0x113c25>
        tank/root/gentoo:<0x113d25>
        tank/root/gentoo:<0x113d28>
        tank/root/gentoo:<0x113d29>
        tank/root/gentoo:<0x113d2c>
        tank/root/gentoo:<0x113d2f>
        tank/root/gentoo:<0x113d30>
        tank/root/gentoo:<0x113d32>
        tank/root/gentoo:<0x113d37>
        tank/root/gentoo:<0x113d3a>
        tank/root/gentoo:<0x113d3d>
        tank/root/gentoo:<0x113d43>
        tank/root/gentoo:<0x113d47>
        tank/root/gentoo:<0x113d48>
        tank/root/gentoo:<0x113d4b>
        tank/root/gentoo:<0x113d4e>
        tank/root/gentoo:<0x113d52>
        tank/root/gentoo:<0x113d57>
        tank/root/gentoo:<0x113d58>
        tank/root/gentoo:<0x113d5c>
        tank/root/gentoo:<0x113d5f>
        tank/root/gentoo:<0x113d60>
        tank/root/gentoo:<0x113d61>
        tank/root/gentoo:<0x113d66>
        tank/root/gentoo:<0x113d6b>
        tank/root/gentoo:<0x113d6d>
        tank/root/gentoo:<0x113d7c>
        tank/root/gentoo:<0x113d7e>
        tank/root/gentoo:<0x113d81>
        tank/root/gentoo:<0x113b8a>
        tank/root/gentoo:<0x113ba6>
        tank/root/gentoo:<0x113bb7>
        tank/root/gentoo:<0x113dba>
        tank/root/gentoo:<0x113bbc>
        tank/root/gentoo:<0x113dbc>
        tank/root/gentoo:<0x113dbe>
        tank/root/gentoo:<0x113bbf>
        tank/root/gentoo:<0x113ccb>
        /usr/portage/.git/index
        /usr/portage/app-backup/amanda/metadata.xml
        /usr/portage/dev-libs/botan/metadata.xml
        /usr/portage/dev-ml/stringext/Manifest
        /usr/portage/dev-ml/stringext/stringext-1.4.2.ebuild
        /usr/portage/dev-ruby/hashie/hashie-3.4.3.ebuild
        /usr/portage/dev-ruby/jmespath/Manifest
        /usr/portage/dev-ruby/jmespath/jmespath-1.2.2.ebuild
        /usr/portage/net-firewall/shorewall/Manifest
        /usr/portage/net-firewall/shorewall/shorewall-5.0.7.2.ebuild
        /usr/portage/net-nds/389-ds-base/389-ds-base-1.3.5.1.ebuild
        /usr/portage/net-nds/389-ds-base/Manifest
        /usr/portage/sys-kernel/rt-sources/Manifest
        /usr/portage/sys-kernel/rt-sources/rt-sources-3.14.65_p68.ebuild
        /usr/portage/sys-kernel/rt-sources/rt-sources-3.18.29_p30.ebuild
        /usr/portage/sys-kernel/rt-sources/rt-sources-4.4.6_p12.ebuild
        /usr/portage/packages/sys-apps/man-pages-4.05.tbz2

**Comment by djdunn** [comment]
3rd scrub cleared everything

**Comment by behlendorf** [comment]
@djdunn I'm glad the third scrub resolved things although it's unclear why it took that many.  Let's close this out for now and if something like this happens again please open a new issue on the zfs issue tracker.
