### ISSUE TITLE
 spl-dkms kernel v4.2 ~ 4.4 = fail

### ISSUE THREAD

**Issue by MasterCATZ** [zfsonlinux/spl#541]
been having problems getting zfs to build / install with kernel 4.x on Ubuntu 14.04.4 LTS
3.19.0-58 was the last running version I had 

I was told last year zfs was 4.2 ready I thought I would have been safe to use it now  
(http://www.phoronix.com/scan.php?page=news_item&px=ZFS-On-Linux-0.6.5)

 sudo apt-get install --reinstall spl-dkms
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libplatform1 linux-image-3.13.0-70-generic
Use 'apt-get autoremove' to remove them.
0 to upgrade, 0 to newly install, 1 to reinstall, 0 to remove and 3 not to upgrade.
Need to get 0 B/370 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 1529880 files and directories currently installed.)
Preparing to unpack .../spl-dkms_0.6.5.6-1~trusty_all.deb ...

-------- Uninstall Beginning --------
Module:  spl
Version: 0.6.5.6
## Kernel:  4.2.0-35-generic (x86_64)

Status: Before uninstall, this module version was ACTIVE on this kernel.

spl.ko:
- Uninstallation
  - Deleting from: /lib/modules/4.2.0-35-generic/updates/dkms/
- Original module
  - No original module was found for this module on this kernel.
  - Use the dkms install command to reinstall any previous module version.

splat.ko:
- Uninstallation
  - Deleting from: /lib/modules/4.2.0-35-generic/updates/dkms/
- Original module
  - No original module was found for this module on this kernel.
  - Use the dkms install command to reinstall any previous module version.

depmod....

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  spl
Version: 0.6.5.6
## Kernel:  4.4.0-18-generic (x86_64)

Status: Before uninstall, this module version was ACTIVE on this kernel.

spl.ko:
- Uninstallation
  - Deleting from: /lib/modules/4.4.0-18-generic/updates/dkms/
- Original module
  - No original module was found for this module on this kernel.
  - Use the dkms install command to reinstall any previous module version.

splat.ko:
- Uninstallation
  - Deleting from: /lib/modules/4.4.0-18-generic/updates/dkms/
- Original module
  - No original module was found for this module on this kernel.
  - Use the dkms install command to reinstall any previous module version.

depmod....

DKMS: uninstall completed.

---

Deleting module version: 0.6.5.6
## completely from the DKMS tree.

Done.
Unpacking spl-dkms (0.6.5.6-1~trusty) over (0.6.5.6-1~trusty) ...
Setting up spl-dkms (0.6.5.6-1~trusty) ...
Loading new spl-0.6.5.6 DKMS files...
Building for 4.2.8-040208-generic and 4.4.6-040406-generic
Building initial module for 4.2.8-040208-generic
configure: error: **\* Unable to build an empty module.
ERROR (dkms apport): kernel package linux-headers-4.2.8-040208-generic is not supported
Error! Bad return status for module build on kernel: 4.2.8-040208-generic (x86_64)
Consult /var/lib/dkms/spl/0.6.5.6/build/make.log for more information.

DKMS make.log for spl-0.6.5.6 for kernel 4.2.8-040208-generic (x86_64)
Mon Apr 18 16:18:32 AEST 2016
make: **\* No targets specified and no makefile found.  Stop.

root@aio:/mnt/Install/gitclone/spl# ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I config
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR,`config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR,`config'.
libtoolize: copying file `config/libtool.m4'
libtoolize: copying file`config/ltoptions.m4'
libtoolize: copying file `config/ltsugar.m4'
libtoolize: copying file`config/ltversion.m4'
libtoolize: copying file `config/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory`.'
root@aio:/mnt/Install/gitclone/spl# ./configure 
checking for gawk... gawk
checking metadata... git describe
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking spl author... OpenZFS on Linux
checking spl license... GPL
checking linux distribution... ubuntu
checking default package type... deb
checking whether rpm is available... yes (4.11.1)
checking whether rpmbuild is available... yes (4.11.1)
checking whether spec files are available... yes (rpm/generic/_.spec.in)
checking whether dpkg is available... yes (1.17.5)
checking whether dpkg-buildpackage is available... yes (1.17.5.)
checking whether alien is available... yes (8.90)
checking spl config... all
checking kernel source directory... /usr/src/linux-headers-4.2.8-040208-generic
checking kernel build directory... /usr/src/linux-headers-4.2.8-040208-generic
checking kernel source version... 4.2.8-040208-generic
checking kernel file name for module symbols... Module.symvers
checking whether debugging is enabled... no
checking whether basic kmem accounting is enabled... no
checking whether detailed kmem tracking is enabled... no
checking whether modules can be built... no
configure: error: *_\* Unable to build an empty module.
root@aio:/mnt/Install/gitclone/spl# 
## *_So I went back to old kernel  *_

> ``

root@aio:~# apt-get remove spl-dkms zfs-dkms ubuntu-zfs
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libplatform1 linux-image-3.13.0-70-generic
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  spl-dkms ubuntu-zfs zfs-dkms
0 to upgrade, 0 to newly install, 3 to remove and 3 not to upgrade.
After this operation, 11.1 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 1529877 files and directories currently installed.)
Removing ubuntu-zfs (8~trusty) ...
Removing zfs-dkms (0.6.5.6-1~trusty) ...

---

Deleting module version: 0.6.5.6
## completely from the DKMS tree.

Done.
Removing spl-dkms (0.6.5.6-1~trusty) ...

---

Deleting module version: 0.6.5.6
## completely from the DKMS tree.

Done.
root@aio:~# apt-get remove spl
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libplatform1 linux-image-3.13.0-70-generic
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  spl
0 to upgrade, 0 to newly install, 1 to remove and 3 not to upgrade.
After this operation, 85.0 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 1529024 files and directories currently installed.)
Removing spl (0.6.5.6-1~trusty) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
root@aio:~# apt-get remove dkms
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libplatform1 linux-image-3.13.0-70-generic
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  dkms
0 to upgrade, 0 to newly install, 1 to remove and 2 not to upgrade.
After this operation, 351 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 1529018 files and directories currently installed.)
Removing dkms (2.2.0.3-1.1ubuntu5.14.04.5) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
root@aio:~# apt-get install debootstrap spl-dkms zfs-dkms ubuntu-zfs
Reading package lists... Done
Building dependency tree  
Reading state information... Done
debootstrap is already the newest version.
The following packages were automatically installed and are no longer required:
  libplatform1 linux-image-3.13.0-70-generic
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  dkms spl
Suggested packages:
  zfs-auto-snapshot
The following NEW packages will be installed:
  dkms spl spl-dkms ubuntu-zfs zfs-dkms
0 to upgrade, 5 to newly install, 0 to remove and 2 not to upgrade.
Need to get 0 B/1,541 kB of archives.
After this operation, 11.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package dkms.
(Reading database ... 1528995 files and directories currently installed.)
Preparing to unpack .../dkms_2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty_all.deb ...
Unpacking dkms (2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty) ...
Selecting previously unselected package spl-dkms.
Preparing to unpack .../spl-dkms_0.6.5.6-1~trusty_all.deb ...
Unpacking spl-dkms (0.6.5.6-1~trusty) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up dkms (2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty) ...
Setting up spl-dkms (0.6.5.6-1~trusty) ...
Loading new spl-0.6.5.6 DKMS files...
First Installation: checking all kernels...
Building for 3.18.10-031810-generic and 4.4.6-040406-generic
Building initial module for 3.18.10-031810-generic
Done.

spl:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/3.18.10-031810-generic/updates/dkms/

splat.ko:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/3.18.10-031810-generic/updates/dkms/

Running the post_install script:

depmod....

DKMS: install completed.
Building initial module for 4.4.6-040406-generic
configure: error: **\* Unable to build an empty module.
ERROR (dkms apport): kernel package linux-headers-4.4.6-040406-generic is not supported
Error! Bad return status for module build on kernel: 4.4.6-040406-generic (x86_64)
Consult /var/lib/dkms/spl/0.6.5.6/build/make.log for more information.
Selecting previously unselected package zfs-dkms.
(Reading database ... 1529305 files and directories currently installed.)
Preparing to unpack .../zfs-dkms_0.6.5.6-1~trusty_amd64.deb ...
Unpacking zfs-dkms (0.6.5.6-1~trusty) ...
Selecting previously unselected package spl.
Preparing to unpack .../spl_0.6.5.6-1~trusty_amd64.deb ...
Unpacking spl (0.6.5.6-1~trusty) ...
Selecting previously unselected package ubuntu-zfs.
Preparing to unpack .../ubuntu-zfs_8~trusty_amd64.deb ...
Unpacking ubuntu-zfs (8~trusty) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up zfs-dkms (0.6.5.6-1~trusty) ...
Loading new zfs-0.6.5.6 DKMS files...
First Installation: checking all kernels...
Building for 3.18.10-031810-generic and 4.4.6-040406-generic
Building initial module for 3.18.10-031810-generic
Done.

zavl:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/3.18.10-031810-generic/updates/dkms/

zcommon.ko:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/3.18.10-031810-generic/updates/dkms/

znvpair.ko:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/3.18.10-031810-generic/updates/dkms/

zpios.ko:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/3.18.10-031810-generic/updates/dkms/

zunicode.ko:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/3.18.10-031810-generic/updates/dkms/

zfs.ko:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/3.18.10-031810-generic/updates/dkms/

depmod....

DKMS: install completed.
Building initial module for 4.4.6-040406-generic
configure: error: 
    **\* Please make sure the kmod spl devel <kernel> package for your
    **\* distribution is installed then try again.  If that fails you
    **\* can specify the location of the spl objects with the
    **\* '--with-spl-obj=PATH' option.
ERROR (dkms apport): kernel package linux-headers-4.4.6-040406-generic is not supported
Error! Bad return status for module build on kernel: 4.4.6-040406-generic (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.6/build/make.log for more information.
Setting up spl (0.6.5.6-1~trusty) ...
Setting up ubuntu-zfs (8~trusty) ...
root@aio:~# modprobe zfs
root@aio:~# dmesg | grep ZFS:
[  586.567015] ZFS: Loaded module v0.6.5.6-1~trusty, ZFS pool version 5000, ZFS filesystem version 5
root@aio:~# 
``

**Comment by behlendorf** [comment]
This definitely does work but there are some rough edges with DKMS builds under certain circumstances.  I'd recommend removing zfs, updating your systems to the latest kernel and kernel headers then reinstalling ZFS.

**Comment by MasterCATZ** [comment]
any other idea as the only thing I did not do was clear my apt cache 
( and I try and keep them so I can roll back )

apt-get purge spl-dkms zfs-dkms ubuntu-zfs spl dkms 

had been performed also 

any particular kernel you have in mind ?
( so far this 4.4 seems to be the more stable video driver for me ) 
linux-headers-4.4.0-18-generic 4.4.0-18.34~14.04.1
 appearers to be the last header my ubuntu install picks up ?

**Comment by behlendorf** [comment]
@MasterCATZ it shouldn't, but if you're using the xenial kernel then you don't need to worry about the DKMS packages at all.  The Ubuntu 4.4 kernel ships with the zfs.ko kernel modules.  All you have to do is install the utilities, the ones from the PPA should be compatible if you can force install them w/out the spl-dkms/zfs-dkms dependency.

**Comment by MasterCATZ** [comment]
well as 16.04 is official soon I decided to upgrade from 14 LTS to 16 LTS 

but still no love getting ZFS working , i'll keep trying things 

for now I broke my flexraid as well ,,, and its backup is on my zfs raidz ... 

root@AIO:~# sudo apt-get install zfsutils-linux zfs-initramfs zfs-zed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libnvpair1linux libuutil1linux libzfs2linux libzpool2linux zfs-doc
Suggested packages:
  default-mta | mail-transport-agent samba-common-bin nfs-kernel-server
The following NEW packages will be installed:
  libnvpair1linux libuutil1linux libzfs2linux libzpool2linux zfs-doc
  zfs-initramfs zfs-zed zfsutils-linux
0 to upgrade, 8 to newly install, 0 to remove and 5 not to upgrade.
Need to get 886 kB of archives.
After this operation, 2,843 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 zfs-doc all 0.6.5.6-0ubuntu7 [47.2 kB]
Get:2 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 libuutil1linux amd64 0.6.5.6-0ubuntu7 [27.4 kB]
Get:3 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 libnvpair1linux amd64 0.6.5.6-0ubuntu7 [23.4 kB]
Get:4 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 libzpool2linux amd64 0.6.5.6-0ubuntu7 [384 kB]
Get:5 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 libzfs2linux amd64 0.6.5.6-0ubuntu7 [106 kB]
Get:6 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 zfsutils-linux amd64 0.6.5.6-0ubuntu7 [266 kB]
Get:7 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 zfs-initramfs all 0.6.5.6-0ubuntu7 [3,912 B]
Get:8 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 zfs-zed amd64 0.6.5.6-0ubuntu7 [29.6 kB]
Fetched 886 kB in 1s (765 kB/s) 
Selecting previously unselected package zfs-doc.
(Reading database ... 175253 files and directories currently installed.)
Preparing to unpack .../zfs-doc_0.6.5.6-0ubuntu7_all.deb ...
Unpacking zfs-doc (0.6.5.6-0ubuntu7) ...
Selecting previously unselected package libuutil1linux.
Preparing to unpack .../libuutil1linux_0.6.5.6-0ubuntu7_amd64.deb ...
Unpacking libuutil1linux (0.6.5.6-0ubuntu7) ...
Selecting previously unselected package libnvpair1linux.
Preparing to unpack .../libnvpair1linux_0.6.5.6-0ubuntu7_amd64.deb ...
Unpacking libnvpair1linux (0.6.5.6-0ubuntu7) ...
Selecting previously unselected package libzpool2linux.
Preparing to unpack .../libzpool2linux_0.6.5.6-0ubuntu7_amd64.deb ...
Unpacking libzpool2linux (0.6.5.6-0ubuntu7) ...
Selecting previously unselected package libzfs2linux.
Preparing to unpack .../libzfs2linux_0.6.5.6-0ubuntu7_amd64.deb ...
Unpacking libzfs2linux (0.6.5.6-0ubuntu7) ...
Selecting previously unselected package zfsutils-linux.
Preparing to unpack .../zfsutils-linux_0.6.5.6-0ubuntu7_amd64.deb ...
Unpacking zfsutils-linux (0.6.5.6-0ubuntu7) ...
Selecting previously unselected package zfs-initramfs.
Preparing to unpack .../zfs-initramfs_0.6.5.6-0ubuntu7_all.deb ...
Unpacking zfs-initramfs (0.6.5.6-0ubuntu7) ...
Selecting previously unselected package zfs-zed.
Preparing to unpack .../zfs-zed_0.6.5.6-0ubuntu7_amd64.deb ...
Unpacking zfs-zed (0.6.5.6-0ubuntu7) ...
Replacing files in old package zfsutils-linux (0.6.5.6-0ubuntu7) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for initramfs-tools (0.122ubuntu8) ...
update-initramfs: Generating /boot/initrd.img-4.4.0-18-generic
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-4ubuntu4) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up zfs-doc (0.6.5.6-0ubuntu7) ...
Setting up libuutil1linux (0.6.5.6-0ubuntu7) ...
Setting up libnvpair1linux (0.6.5.6-0ubuntu7) ...
Setting up libzpool2linux (0.6.5.6-0ubuntu7) ...
Setting up libzfs2linux (0.6.5.6-0ubuntu7) ...
Setting up zfsutils-linux (0.6.5.6-0ubuntu7) ...
zfs-import-cache.service is a disabled or a static unit, not starting it.
zfs-import-scan.service is a disabled or a static unit, not starting it.
zfs-mount.service is a disabled or a static unit, not starting it.
A dependency job for zfs.target failed. See 'journalctl -xe' for details.
zfs.target couldn't start.
Processing triggers for initramfs-tools (0.122ubuntu8) ...
update-initramfs: Generating /boot/initrd.img-4.4.0-18-generic
Setting up zfs-zed (0.6.5.6-0ubuntu7) ...
zed.service is a disabled or a static unit, not starting it.
Setting up zfs-initramfs (0.6.5.6-0ubuntu7) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-4ubuntu4) ...
Processing triggers for initramfs-tools (0.122ubuntu8) ...
update-initramfs: Generating /boot/initrd.img-4.4.0-18-generic
root@AIO:~# sudo modprobe zfs
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.5.1-040501-generic/modules.dep.bin'
modprobe: FATAL: Module zfs not found in directory /lib/modules/4.5.1-040501-generic
root@AIO:~#

**Comment by behlendorf** [comment]
Closing as stale.  ZFS is now provided as part of Ubuntu.
