### ISSUE TITLE
spl_hostid= kernel parameter ignored by spl

### ISSUE THREAD

**Issue by kostyaberger** [zfsonlinux/spl#544]
Hello everyone,
I'm trying to use spl_hostid kernel parameter, but it seems to be recognized only by zfs, while spl sets its own hostid, which is clear from the boot message.

There was some comment a year ago about it, but what is actually the current state of this? Can I somehow set a constant hostid? I have 2 OSs in my zpool, FreeBSD and Linux -- this is just what I'm testing, if they can be used in the same rpool which occupies the whole disk.

Now FreeBSD has no problem using the pool because Linux exports it upon shutdown/reboot. But FreeBSD does not, so Linux has to face the "pool used by another system" problem. It can be overridden by zfs_force=1 AFAIK, but I'd prefer the hostid method.

**Comment by kostyaberger** [comment]
Ok, it's my lack of attention: the parameter is spl.spl_hostid and it works.

**Comment by kostyaberger** [comment]
Since I've opened this, the last question: setting hostid in /etc/hostid doesn't seem to work the way I expected. That is, say, my hostid is 0x6decea31 and works fine when set via spl.spl_hostid. But will it work the same if I put that string into /etc/hostid?

**Comment by rlaager** [comment]
Don't put that string into /etc/hostid, put those bytes into /etc/hostid.

**Comment by kostyaberger** [comment]
Yrs, thank you. Just for technical reasons I can't create a new initramfs now to test it, but as soon as i get to it i'll test it.
