### ISSUE TITLE
mutex_init is redefined but fs.h is included

### ISSUE THREAD

**Issue by BigTheta** [zfsonlinux/spl#555]
I'm trying to compile spl against a kernel source (version 3.7).

I get the error some other users have in other closed issues about mutex init expecting 4 parameters.

I see in include/sys/mutex.h mutex_init is redefined. The issue is that since linux/fs.h is included, in several files, a use of mutex_init from the kernel (include/linux/percpu-rwsem.h included by fs.h) prevents the module from compiling. 

It appears to be an issue with a older kernel versions for anybody who wants to compile against sources instead of headers. But the SPL 0.6.5 changelog says "Compatible with 2.6.32 - 4.2 Linux kernels" so it should definitely work with 3.7

Edit: Upon further inspection, it appears 3.7 is only kernel this will be problem with. And it should also affect regular header compilation. 3.7 was the first version that included the percpu-rwsem.h file and 3.8 replaced mutex_init with  __percpu_init_rwsem

**Comment by behlendorf** [comment]
Closing.  Only the 3.7 kernel has this issue.
