### ISSUE TITLE
Strange #define in sys/cred.h

### ISSUE THREAD

**Issue by tuxoko** [zfsonlinux/spl#559]
https://github.com/zfsonlinux/spl/blob/master/include/sys/cred.h#L46
This doesn't make any sense.

**Comment by behlendorf** [comment]
I'm not sure what this is all about either.

**Comment by DeHackEd** [comment]
Linux 3.8 (user namespaces) redefines `uid_t` and `gid_t` (integer types) into `kuid_t` and `kgid_t` (structure types) to force API breakage in modules that don't handle UIDs using namespace-aware functions. At least when the user namespaces feature is enabled.

My guess is this was an attempt to maintain access to the integer types which can be configured for either 32 bit or 16 bit (historic) mode for embedded systems, and ended up not being used in the end.

**Comment by behlendorf** [comment]
Fixed by #569
