### ISSUE TITLE
Linux 4.9 build failures

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/spl#579]
The latest unreleased kernel.org kernel is causing the following build failures which need to be investigated.

http://build.zfsonlinux.org/builders/Kernel.org%20Default%20x86_64%20%28BUILD%29/builds/8803/steps/shell_2/logs/make

**Comment by eikel** [comment]
After updating to Linux kernel 4.9 on my Debian system I also see the error “incompatible type for argument 1 of ‘__kgid_val’” you reported. I additionally created a [downstream bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851352).

**Comment by achims311** [comment]
There is already a fix for it:
https://github.com/zfsonlinux/spl/commit/ae7eda1dde8aebc298a013254dcd90f7fa42171a
But this is only on master, , and does not applz cleanly on the 0.6.5.8 brach, which is the right one for debian.

**Comment by behlendorf** [comment]
This fix will be pull in to the 0.6.5-release branch for the 0.6.5.9 tag.

**Comment by demizer** [comment]
Stable release for Arch Linux is blocked as we are currently using 4.9 kernel. See https://github.com/archzfs/archzfs/issues/98

Thanks!

**Comment by behlendorf** [comment]
@demizer thanks for the heads up.  A updated tag is on the way.

**Comment by behlendorf** [comment]
The [0.6.5.9 release](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.9) is tagged and available.  Sorry about the delay.

**Comment by demizer** [comment]
Thank you! @behlendorf
