### ISSUE TITLE
Running the post_install script issue 0.6.5.8

### ISSUE THREAD

**Issue by ochbob** [zfsonlinux/spl#602]
Hello,

i try to install spl module with dkms, everything seems to be fine, expectly the end when the post_install script is called:

> Running the post_install script:
> cp: impossible d'évaluer « /var/lib/dkms/spl/0.6.5.8/build/spl_config.h »: Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer « /var/lib/dkms/spl/0.6.5.8/build/module/Module.symvers »: Aucun fichier ou dossier de ce type

I don't have any "build" folder into /var/lib/dkms/spl/0.6.5.8/

I found this one: https://groups.google.com/forum/#!topic/linux.debian.bugs.dist/OFefIC5NCUI

but my /usr/src/spl-0.6.5.8/dkms.conf is good:

> POST_BUILD="cp
>   ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/spl_config.h
>   ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/module/Module.symvers
>   ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/${kernelver}/${arch}/
> "

Any idea ? i can't figure out with this issue...

And what exactly do the post_install script ?

More information:
apt-cache policy spl
  Installé : 0.6.5.8-3~bpo8+1

apt-cache policy spl-dkms
  Installé : 0.6.5.8-3~bpo8+1

**Comment by kandeshvari** [comment]
just place `cp` script to `/var/lib/dkms/spl/0.6.5.8/source`

```
#!/bin/sh
cp "$@"
```
