### ISSUE TITLE
Kernel.org builders failing because set_task_state() removed from kernel

### ISSUE THREAD

**Issue by ofaaland** [zfsonlinux/spl#604]
Kernel.org builds are failing because torvalds/linux@642fa44 removed set_task_state():

spl/spl/spl-err.c: In function ‘spl_panic’:
spl/spl/spl-err.c:68:2: error: implicit declaration of function ‘set_task_state’ [-Werror=implicit-function-declaration]
  set_task_state(current, TASK_UNINTERRUPTIBLE);

spl PR 603 has been submitted to address this.

**Comment by kernelOfTruth** [comment]
can be closed since #603 got merged (https://github.com/zfsonlinux/spl/pull/603)

CC: @behlendorf

**Comment by dinatale2** [comment]
Closing since this has been resolved.
