### ISSUE TITLE
spl dkms fails to build on 4.11

### ISSUE THREAD

**Issue by floli** [zfsonlinux/spl#618]
Hello,
on my Arch, using kernel 4.11.2, spl fails to build:

```
root@marduk / # dkms status
spl, 0.6.5.9, 4.10.5-1-ARCH, x86_64: installed
spl, 0.6.5.9, 4.9.29-1-lts, x86_64: installed
zfs, 0.6.5.9, 4.9.17-1-lts, x86_64: installed

root@marduk / # dkms autoinstall

Kernel preparation unnecessary for this kernel.  Skipping...

Running the pre_build script:
checking for gawk... gawk
checking metadata... META file
[...]
checking whether header linux/sched/rt.h exists... yes
checking whether vfs_getattr() wants... configure: error: unknown

Building module:
cleaning build area...(bad exit status: 2)
make -j4 KERNELRELEASE=4.11.2-1-ARCH...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.11.2-1-ARCH (x86_64)
Consult /var/lib/dkms/spl/0.6.5.9/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Running the pre_build script:
checking for gawk... gawk
[...]
checking spl source directory... /usr/src/spl-0.6.5.9
checking spl build directory... /var/lib/dkms/spl/0.6.5.9/4.11.2-1-ARCH/x86_64
configure: error: 
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.

Building module:
cleaning build area...(bad exit status: 2)
make -j4 KERNELRELEASE=4.11.2-1-ARCH...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.11.2-1-ARCH (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.9/build/make.log for more information.
```
```checking spl build directory...``` takes a very long time.

make.log contains nothing useful.
```
root@marduk / # cat /var/lib/dkms/zfs/0.6.5.9/build/make.log
DKMS make.log for zfs-0.6.5.9 for kernel 4.11.2-1-ARCH (x86_64)
Fr 26. Mai 10:14:50 CEST 2017
make: *** Es wurden keine Ziele angegeben und keine „make“-Steuerdatei gefunden.  Schluss.
```
(no targets given and no makefile found)

``` /var/lib/dkms/spl/0.6.5.9/4.11.2-1-ARCH/``` does not exist, creating it changed nothing.

Any ideas for me?

Thanks!

**Comment by ecraven** [comment]
I've run into the exact same problem, also commented here:
https://aur.archlinux.org/packages/spl-dkms/

**Comment by tonyhutter** [comment]
FYI - I've been putting together patches for a new 0.6.5.10 release (SPL: https://github.com/zfsonlinux/spl/pull/615, ZFS: https://github.com/zfsonlinux/zfs/pull/6142).  A number of the patches are 4.11+ kernel fixes, which may or may not fix this particular issue.

**Comment by alexmarkley** [comment]
I am having this issue as well on Fedora 25. It's showing up in the spl-dkms-0.6.5.9-1.fc25.noarch.rpm package from the official release repository. Became an issue as soon as Fedora pushed 4.11.3-200.fc25 into the stable updates repo.

**Comment by kpande** [comment]
because 4.11 isn't supported by 0.6.5, please read the release notes..

**Comment by tonyhutter** [comment]
0.6.5.10 was released last week (https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.10).  It builds both under the 4.11 kernel and Fedora 25.   Can you give it a try and let us know if you still see the same build issue?

**Comment by alexmarkley** [comment]
I am happy to report that with 0.6.5.10 the reported issue is no longer affecting me.

Here is the configuration of my production system:

```
[alex@elbmin ~]$ uname -s -r
Linux 4.11.5-200.fc25.x86_64
[alex@elbmin ~]$ rpm -qa | egrep 'spl-dkms|zfs-dkms' | sort
spl-dkms-0.6.5.10-1.fc25.noarch
zfs-dkms-0.6.5.10-1.fc25.noarch
[alex@elbmin ~]$
```

Thanks for working on this!

**Comment by tonyhutter** [comment]
Looks like 0.6.5.10 fixes this.  Closing issue
