### ISSUE TITLE
spl dkms fails to build on 4.11.9-1-vfio

### ISSUE THREAD

**Issue by ram4444** [zfsonlinux/spl#631]
Same problem as https://github.com/zfsonlinux/spl/issues/618
-------------------------------------------------------------------------
Here is the error log when installing linux-vfio
:: Running pre-transaction hooks...
(1/1) Remove DKMS modules
==> dkms remove zfs/0.6.5.10 -k 4.11.9-1-vfio
==> dkms remove spl/0.6.5.10 -k 4.11.9-1-vfio
:: Processing package changes...
(1/3) reinstalling linux-vfio [######################] 100%
>>> Updating module dependencies. Please wait ...
(2/3) reinstalling linux-vfio-docs [######################] 100%
(3/3) reinstalling linux-vfio-headers [######################] 100%
:: Running post-transaction hooks...
(1/3) Install DKMS modules
==> dkms install zfs/0.6.5.10 -k 4.11.9-1-vfio
configure: error: 
*** Please make sure the kmod spl devel <kernel> package for your
*** distribution is installed then try again. If that fails you
*** can specify the location of the spl objects with the
*** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 4.11.9-1-vfio (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.10/build/make.log for more information.

--------------------------------------------------------------------------
Here is the error log when installing zfs-dkms alone:

checking zfs config... kernel
checking for -Wno-unused-but-set-variable support... yes
checking for -Wno-bool-compare support... yes
checking kernel source directory... /usr/lib/modules/4.11.9-1-vfio/build
checking kernel build directory... /usr/lib/modules/4.11.9-1-vfio/build
checking kernel source version... 4.11.9-1-vfio
checking kernel file name for module symbols... Module.symvers
checking spl source directory... /usr/src/spl-0.6.5.10
checking spl build directory... /var/lib/dkms/spl/0.6.5.10/4.11.9-1-vfio/x86_64
configure: error: 
	*** Please make sure the kmod spl devel <kernel> package for your
	*** distribution is installed then try again.  If that fails you
	*** can specify the location of the spl objects with the
	*** '--with-spl-obj=PATH' option.

Building module:
cleaning build area...(bad exit status: 2)
make -j12 KERNELRELEASE=4.11.9-1-vfio...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.11.9-1-vfio (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.10/build/make.log for more information.
------------------------------------------------------------
It is shown that the installaion knows the spl dependency, but installation cant continue after zfs as dependency may be in wrong order.

**Comment by minextu** [comment]
This is an issue with Archlinux and not SPL/ZFS itself (https://bugs.archlinux.org/task/52901). 

You can either install dkms-sorted or manually run the dkms build after spl. The dkms packages in archzfs have a workaround for that, too.

**Comment by behlendorf** [comment]
Closing. Packages will be merged I  the next release removing the ordering issue.
