### ISSUE TITLE
spl: Unknown symbol vfs_read (err 0)

### ISSUE THREAD

**Issue by krichter722** [zfsonlinux/spl#656]
After installing Ubuntu 4.14-rc3 mainline kernel for verification of an issue, I noticed that after building and installing spl and zfs with `git clean -x -f -d && ./autogen.sh && ./configure && make && sudo make install && sudo make deb-kmod && sudo dpkg -i *.deb` like I do on standard Ubuntu kernels (+ removing `/lib/modules/[version]/kernel/zfs` and `sudo depmod -a` which I don't have to do for mainline kernels because there's no `/lib/modules/[version]/kernel/zfs`) `modprobe zfs`  fails with

    modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)

and `dmesg` contains

    [  941.174786] spl: Unknown symbol vfs_write (err 0)
    [  941.174865] spl: Unknown symbol vfs_read (err 0)

I'm not very eager to use the kernel, I just wanted to bring this to the attention of the devs, but I can re-install it and provide further information in case you can't reproduce the issue.

experienced with spl 0.7.0-13_ge8474f9a and 0.7.0-99_g39f56627a on Ubuntu 17.04 amd64

**Comment by loli10K** [comment]
https://github.com/torvalds/linux/commit/bd8df82be66698042d11e7919e244c8d72b042ca: _fs: unexport vfs_read and vfs_write_

>No modular users left.  Given that they take user pointers there is no
>good reason to export it to drivers to start with.

**Comment by behlendorf** [comment]
Initial patch in https://github.com/zfsonlinux/spl/pull/659 for review.
