### ISSUE TITLE
"make pkg-dkms" fails due to "error: bad date in %changelog: So Okt 22 2017 Brian Behlendorf <behlendorf1@llnl.gov> 0.7.0-17_g28920ea"

### ISSUE THREAD

**Issue by krichter722** [zfsonlinux/spl#663]
I'm not sure about the state of DKMS installation from source (i saw that #657 has been merged), but I'd like to make sure that the following issue is noticed in case it's already considered working: `./autogen.sh && ./configure && make && make pkg-dkms` fails due to

```
make[2]: Entering directory '/mnt/data/sources/spl'
make[2]: Leaving directory '/mnt/data/sources/spl'
error: bad date in %changelog: So Okt 22 2017 Brian Behlendorf <behlendorf1@llnl.gov> 0.7.0-17_g28920ea
Makefile:1058: recipe for target 'srpm-common' failed
make[1]: *** [srpm-common] Error 1
make[1]: Leaving directory '/mnt/data/sources/spl'
Makefile:1014: recipe for target 'srpm-dkms' failed
make: *** [srpm-dkms] Error 2
```

<details>
<summary>build output</summary>
<pre>
> ./autogen.sh && ./configure && make && make pkg-dkms
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I config
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'config'.
libtoolize: copying file 'config/libtool.m4'
libtoolize: copying file 'config/ltoptions.m4'
libtoolize: copying file 'config/ltsugar.m4'
libtoolize: copying file 'config/ltversion.m4'
libtoolize: copying file 'config/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:43: installing 'config/compile'
configure.ac:33: installing 'config/config.guess'
configure.ac:33: installing 'config/config.sub'
configure.ac:36: installing 'config/install-sh'
configure.ac:36: installing 'config/missing'
cmd/splat/Makefile.am: installing 'config/depcomp'
autoreconf: Leaving directory `.'
checking for gawk... gawk
checking metadata... git describe
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking spl author... OpenZFS on Linux
checking spl license... GPL
checking linux distribution... ubuntu
checking default package type... deb
checking whether rpm is available... yes (4.12.0.2)
checking whether rpmbuild is available... yes (4.12.0.2)
checking whether spec files are available... yes (rpm/generic/*.spec.in)
checking whether dpkg is available... yes (1.18.24)
checking whether dpkg-buildpackage is available... yes (1.18.24.)
checking whether alien is available... yes (8.95)
checking spl config... all
checking kernel source directory... /usr/src/linux-headers-4.13.0-16-generic
checking kernel build directory... /usr/src/linux-headers-4.13.0-16-generic
checking kernel source version... 4.13.0-16-generic
checking kernel file name for module symbols... Module.symvers
checking whether debugging is enabled... no
checking whether basic kmem accounting is enabled... no
checking whether detailed kmem tracking is enabled... no
checking whether modules can be built... yes
checking whether atomic types use spinlocks... no
checking whether kernel defines atomic64_t... yes
checking whether old 2-argument shrinker exists... no
checking whether old 3-argument shrinker exists... no
checking whether new 2-argument shrinker exists... no
checking whether ->count_objects callback exists... yes
checking whether struct ctl_table has ctl_name... no
checking whether CONFIG_TRIM_UNUSED_KSYM is disabled... yes
checking whether PDE_DATA() is available... yes
checking whether set_fs_pwd() requires const struct path *... yes
checking whether vfs_unlink() wants 2 args... no
checking whether vfs_unlink() wants 3 args... yes
checking whether vfs_rename() wants 4 args... no
checking whether vfs_rename() wants 5 args... no
checking whether vfs_rename() wants 6 args... yes
checking whether vfs_fsync() wants 2 args... yes
checking whether truncate_range() inode operation is available... no
checking whether struct fs_struct uses spinlock_t... yes
checking whether kuid_t/kgid_t is available... yes; mandatory
checking whether fops->fallocate() exists... yes
checking whether iops->fallocate() exists... no
checking whether fops->fallocate() exists... no
checking whether CONFIG_ZLIB_INFLATE is defined... yes
checking whether CONFIG_ZLIB_DEFLATE is defined... yes
checking whether zlib_deflate_workspacesize() wants 2 args... yes
checking whether struct shrink_control exists... yes
checking whether struct rw_semaphore member wait_lock is raw... yes
checking whether struct rw_semaphore has member activity... no
checking whether struct rw_semaphore has atomic_long_t member count... yes
checking whether header linux/sched/rt.h exists... yes
checking whether header linux/sched/signal.h exists... yes
checking whether vfs_getattr() wants 4 args... yes
checking whether vfs_getattr() wants 3 args... no
checking whether vfs_getattr() wants 2 args... no
checking whether usleep_range() is available... yes
checking whether struct kmem_cache has allocflags... no
checking whether struct kmem_cache has gfpflags... no
checking whether wait_on_bit() takes an action... no
checking whether inode_lock_shared() exists... yes
checking whether group_info->gid exists... yes
checking whether kmem_cache_create_usercopy() exists... no
checking whether wait_queue_entry_t exists... yes
checking whether wq_head->head and wq_entry->entry exist... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating man/Makefile
config.status: creating man/man1/Makefile
config.status: creating man/man5/Makefile
config.status: creating lib/Makefile
config.status: creating cmd/Makefile
config.status: creating cmd/splat/Makefile
config.status: creating cmd/splslab/Makefile
config.status: creating module/Makefile
config.status: creating module/spl/Makefile
config.status: creating module/splat/Makefile
config.status: creating include/Makefile
config.status: creating include/fs/Makefile
config.status: creating include/linux/Makefile
config.status: creating include/rpc/Makefile
config.status: creating include/sharefs/Makefile
config.status: creating include/sys/Makefile
config.status: creating include/sys/fm/Makefile
config.status: creating include/sys/fs/Makefile
config.status: creating include/sys/sysevent/Makefile
config.status: creating include/util/Makefile
config.status: creating include/vm/Makefile
config.status: creating scripts/Makefile
config.status: creating rpm/Makefile
config.status: creating rpm/redhat/Makefile
config.status: creating rpm/redhat/spl.spec
config.status: creating rpm/redhat/spl-kmod.spec
config.status: creating rpm/redhat/spl-dkms.spec
config.status: creating rpm/generic/Makefile
config.status: creating rpm/generic/spl.spec
config.status: creating rpm/generic/spl-kmod.spec
config.status: creating rpm/generic/spl-dkms.spec
config.status: creating spl.release
config.status: creating spl_config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make  all-recursive
make[1]: Entering directory '/mnt/data/sources/spl'
Making all in include
make[2]: Entering directory '/mnt/data/sources/spl/include'
Making all in fs
make[3]: Entering directory '/mnt/data/sources/spl/include/fs'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/data/sources/spl/include/fs'
Making all in linux
make[3]: Entering directory '/mnt/data/sources/spl/include/linux'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/data/sources/spl/include/linux'
Making all in rpc
make[3]: Entering directory '/mnt/data/sources/spl/include/rpc'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/data/sources/spl/include/rpc'
Making all in sharefs
make[3]: Entering directory '/mnt/data/sources/spl/include/sharefs'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/data/sources/spl/include/sharefs'
Making all in sys
make[3]: Entering directory '/mnt/data/sources/spl/include/sys'
Making all in fm
make[4]: Entering directory '/mnt/data/sources/spl/include/sys/fm'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/mnt/data/sources/spl/include/sys/fm'
Making all in fs
make[4]: Entering directory '/mnt/data/sources/spl/include/sys/fs'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/mnt/data/sources/spl/include/sys/fs'
Making all in sysevent
make[4]: Entering directory '/mnt/data/sources/spl/include/sys/sysevent'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/mnt/data/sources/spl/include/sys/sysevent'
make[4]: Entering directory '/mnt/data/sources/spl/include/sys'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/mnt/data/sources/spl/include/sys'
make[3]: Leaving directory '/mnt/data/sources/spl/include/sys'
Making all in util
make[3]: Entering directory '/mnt/data/sources/spl/include/util'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/data/sources/spl/include/util'
Making all in vm
make[3]: Entering directory '/mnt/data/sources/spl/include/vm'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/data/sources/spl/include/vm'
make[3]: Entering directory '/mnt/data/sources/spl/include'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/mnt/data/sources/spl/include'
make[2]: Leaving directory '/mnt/data/sources/spl/include'
Making all in rpm
make[2]: Entering directory '/mnt/data/sources/spl/rpm'
Making all in generic
make[3]: Entering directory '/mnt/data/sources/spl/rpm/generic'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/data/sources/spl/rpm/generic'
Making all in redhat
make[3]: Entering directory '/mnt/data/sources/spl/rpm/redhat'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/data/sources/spl/rpm/redhat'
make[3]: Entering directory '/mnt/data/sources/spl/rpm'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/mnt/data/sources/spl/rpm'
make[2]: Leaving directory '/mnt/data/sources/spl/rpm'
Making all in lib
make[2]: Entering directory '/mnt/data/sources/spl/lib'
  CC       list.lo
  CCLD     libcommon.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/mnt/data/sources/spl/lib'
Making all in cmd
make[2]: Entering directory '/mnt/data/sources/spl/cmd'
Making all in splat
make[3]: Entering directory '/mnt/data/sources/spl/cmd/splat'
  CC       splat.o
  CCLD     splat
make[3]: Leaving directory '/mnt/data/sources/spl/cmd/splat'
Making all in splslab
make[3]: Entering directory '/mnt/data/sources/spl/cmd/splslab'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/data/sources/spl/cmd/splslab'
make[3]: Entering directory '/mnt/data/sources/spl/cmd'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/mnt/data/sources/spl/cmd'
make[2]: Leaving directory '/mnt/data/sources/spl/cmd'
Making all in man
make[2]: Entering directory '/mnt/data/sources/spl/man'
Making all in man1
make[3]: Entering directory '/mnt/data/sources/spl/man/man1'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/data/sources/spl/man/man1'
Making all in man5
make[3]: Entering directory '/mnt/data/sources/spl/man/man5'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/data/sources/spl/man/man5'
make[3]: Entering directory '/mnt/data/sources/spl/man'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/mnt/data/sources/spl/man'
make[2]: Leaving directory '/mnt/data/sources/spl/man'
Making all in scripts
make[2]: Entering directory '/mnt/data/sources/spl/scripts'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/mnt/data/sources/spl/scripts'
Making all in module
make[2]: Entering directory '/mnt/data/sources/spl/module'
make -C /usr/src/linux-headers-4.13.0-16-generic SUBDIRS=`pwd`  CONFIG_SPL=m modules
make[3]: Entering directory '/usr/src/linux-headers-4.13.0-16-generic'
  CC [M]  /mnt/data/sources/spl/module/spl/spl-proc.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-ctl.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-kmem.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-kmem.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-kmem-cache.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-taskq.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-vmem.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-random.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-thread.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-mutex.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-rwlock.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-rwlock.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-condvar.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-vnode.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-taskq.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-thread.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-err.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-time.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-kobj.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-generic.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-vnode.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-atomic.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-mutex.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-kobj.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-kstat.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-atomic.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-generic.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-list.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-condvar.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-xdr.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-cred.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-cred.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-tsd.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-zlib.o
  CC [M]  /mnt/data/sources/spl/module/splat/splat-linux.o
  CC [M]  /mnt/data/sources/spl/module/spl/spl-zlib.o
  LD [M]  /mnt/data/sources/spl/module/spl/spl.o
  LD [M]  /mnt/data/sources/spl/module/splat/splat.o
  Building modules, stage 2.
  MODPOST 2 modules
  CC      /mnt/data/sources/spl/module/spl/spl.mod.o
  CC      /mnt/data/sources/spl/module/splat/splat.mod.o
  LD [M]  /mnt/data/sources/spl/module/spl/spl.ko
  LD [M]  /mnt/data/sources/spl/module/splat/splat.ko
make[3]: Leaving directory '/usr/src/linux-headers-4.13.0-16-generic'
make[2]: Leaving directory '/mnt/data/sources/spl/module'
make[2]: Entering directory '/mnt/data/sources/spl'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/mnt/data/sources/spl'
make[1]: Leaving directory '/mnt/data/sources/spl'
make  pkg="spl-dkms" \
	def='--define "build_src_rpm 1" ' srpm-common
make[1]: Entering directory '/mnt/data/sources/spl'
make  dist-gzip am__post_remove_distdir='@:'
make[2]: Entering directory '/mnt/data/sources/spl'
if test -d "spl-0.7.0"; then find "spl-0.7.0" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "spl-0.7.0" || { sleep 5 && rm -rf "spl-0.7.0"; }; else :; fi
test -d "spl-0.7.0" || mkdir "spl-0.7.0"
 (cd include && make  top_distdir=../spl-0.7.0 distdir=../spl-0.7.0/include \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory '/mnt/data/sources/spl/include'
 (cd fs && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/include/fs \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/include/fs'
make[4]: Leaving directory '/mnt/data/sources/spl/include/fs'
 (cd linux && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/include/linux \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/include/linux'
make[4]: Leaving directory '/mnt/data/sources/spl/include/linux'
 (cd rpc && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/include/rpc \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/include/rpc'
make[4]: Leaving directory '/mnt/data/sources/spl/include/rpc'
 (cd sharefs && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/include/sharefs \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/include/sharefs'
make[4]: Leaving directory '/mnt/data/sources/spl/include/sharefs'
 (cd sys && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/include/sys \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/include/sys'
 (cd fm && make  top_distdir=../../../spl-0.7.0 distdir=../../../spl-0.7.0/include/sys/fm \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[5]: Entering directory '/mnt/data/sources/spl/include/sys/fm'
make[5]: Leaving directory '/mnt/data/sources/spl/include/sys/fm'
 (cd fs && make  top_distdir=../../../spl-0.7.0 distdir=../../../spl-0.7.0/include/sys/fs \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[5]: Entering directory '/mnt/data/sources/spl/include/sys/fs'
make[5]: Leaving directory '/mnt/data/sources/spl/include/sys/fs'
 (cd sysevent && make  top_distdir=../../../spl-0.7.0 distdir=../../../spl-0.7.0/include/sys/sysevent \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[5]: Entering directory '/mnt/data/sources/spl/include/sys/sysevent'
make[5]: Leaving directory '/mnt/data/sources/spl/include/sys/sysevent'
make[4]: Leaving directory '/mnt/data/sources/spl/include/sys'
 (cd util && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/include/util \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/include/util'
make[4]: Leaving directory '/mnt/data/sources/spl/include/util'
 (cd vm && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/include/vm \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/include/vm'
make[4]: Leaving directory '/mnt/data/sources/spl/include/vm'
make[3]: Leaving directory '/mnt/data/sources/spl/include'
 (cd rpm && make  top_distdir=../spl-0.7.0 distdir=../spl-0.7.0/rpm \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory '/mnt/data/sources/spl/rpm'
 (cd generic && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/rpm/generic \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/rpm/generic'
make[4]: Leaving directory '/mnt/data/sources/spl/rpm/generic'
 (cd redhat && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/rpm/redhat \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/rpm/redhat'
make[4]: Leaving directory '/mnt/data/sources/spl/rpm/redhat'
make[3]: Leaving directory '/mnt/data/sources/spl/rpm'
 (cd lib && make  top_distdir=../spl-0.7.0 distdir=../spl-0.7.0/lib \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory '/mnt/data/sources/spl/lib'
make[3]: Leaving directory '/mnt/data/sources/spl/lib'
 (cd cmd && make  top_distdir=../spl-0.7.0 distdir=../spl-0.7.0/cmd \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory '/mnt/data/sources/spl/cmd'
 (cd splat && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/cmd/splat \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/cmd/splat'
make[4]: Leaving directory '/mnt/data/sources/spl/cmd/splat'
 (cd splslab && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/cmd/splslab \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/cmd/splslab'
make[4]: Leaving directory '/mnt/data/sources/spl/cmd/splslab'
make[3]: Leaving directory '/mnt/data/sources/spl/cmd'
 (cd man && make  top_distdir=../spl-0.7.0 distdir=../spl-0.7.0/man \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory '/mnt/data/sources/spl/man'
 (cd man1 && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/man/man1 \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/man/man1'
make[4]: Leaving directory '/mnt/data/sources/spl/man/man1'
 (cd man5 && make  top_distdir=../../spl-0.7.0 distdir=../../spl-0.7.0/man/man5 \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory '/mnt/data/sources/spl/man/man5'
make[4]: Leaving directory '/mnt/data/sources/spl/man/man5'
make[3]: Leaving directory '/mnt/data/sources/spl/man'
 (cd scripts && make  top_distdir=../spl-0.7.0 distdir=../spl-0.7.0/scripts \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory '/mnt/data/sources/spl/scripts'
make[3]: Leaving directory '/mnt/data/sources/spl/scripts'
 (cd module && make  top_distdir=../spl-0.7.0 distdir=../spl-0.7.0/module \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory '/mnt/data/sources/spl/module'
list='spl splat'; for subdir in $list; do \
	(find ../module/$subdir -name '*.c' -o -name '*.h' |\
	 xargs /bin/cp -t $distdir/$subdir); \
done
make[3]: Leaving directory '/mnt/data/sources/spl/module'
make  \
  top_distdir="spl-0.7.0" distdir="spl-0.7.0" \
  dist-hook
make[3]: Entering directory '/mnt/data/sources/spl'
sed -i 's/Release:[[:print:]]*/Release:      17_g28920ea/' \
	spl-0.7.0/META
make[3]: Leaving directory '/mnt/data/sources/spl'
test -n "" \
|| find "spl-0.7.0" -type d ! -perm -755 \
	-exec chmod u+rwx,go+rx {} \; -o \
  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -444 -exec /bin/bash /mnt/data/sources/spl/config/install-sh -c -m a+r {} {} \; \
|| chmod -R a+r "spl-0.7.0"
tardir=spl-0.7.0 && ${TAR-tar} chof - "$tardir" | GZIP=--best gzip -c >spl-0.7.0.tar.gz
make[2]: Leaving directory '/mnt/data/sources/spl'
if test -d "spl-0.7.0"; then find "spl-0.7.0" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "spl-0.7.0" || { sleep 5 && rm -rf "spl-0.7.0"; }; else :; fi
make[2]: Entering directory '/mnt/data/sources/spl'
make[2]: Leaving directory '/mnt/data/sources/spl'
error: bad date in %changelog: So Okt 22 2017 Brian Behlendorf <behlendorf1@llnl.gov> 0.7.0-17_g28920ea
Makefile:1058: recipe for target 'srpm-common' failed
make[1]: *** [srpm-common] Error 1
make[1]: Leaving directory '/mnt/data/sources/spl'
Makefile:1014: recipe for target 'srpm-dkms' failed
make: *** [srpm-dkms] Error 2
</pre>
</details>

experienced with spl-0.7.0-17-g28920ea on Ubuntu 17.10

**Comment by creshal** [comment]
`LC_TIME=C make pkg-dkms` works around this issue; whatever script is generating the changelog date string should set it internally.

**Comment by krichter722** [comment]
This no longer works for tag `spl-0.7.9` on Ubuntu 18.04, but that shouldn't matter because 'spl` is integrated into `zfs` as far as I understand and thus no longer necessary for building `zfs` > 0.7.9.
