### ISSUE TITLE
spl-0.7.6: compile error

### ISSUE THREAD

**Issue by emcepe** [zfsonlinux/spl#683]
gcc version 7.3.0 (Debian 7.3.0-3)
Kernel 4.14.19 with grsec patch

make[2]: Entering directory '/var/lib/dkms/spl/0.7.6/build/module'
make -C /lib/modules/4.14.19-grsec/build SUBDIRS=`pwd`  O=/lib/modules/4.14.19-grsec/build CONFIG_SPL=m modules
make[3]: Entering directory '/usr/src/linux-4.14.19-grsec'
make[4]: Entering directory '/usr/src/linux-4.14.19-grsec'
  CC [M]  /var/lib/dkms/spl/0.7.6/build/module/splat/splat-ctl.o
  CC [M]  /var/lib/dkms/spl/0.7.6/build/module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.7.6/build/module/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/spl/0.7.6/build/module/splat/splat-kmem.o
  CC [M]  /var/lib/dkms/spl/0.7.6/build/module/spl/spl-kmem-cache.o
  CC [M]  /var/lib/dkms/spl/0.7.6/build/module/splat/splat-taskq.o
  CC [M]  /var/lib/dkms/spl/0.7.6/build/module/spl/spl-vmem.o
  CC [M]  /var/lib/dkms/spl/0.7.6/build/module/splat/splat-random.o
In file included from /var/lib/dkms/spl/0.7.6/build/module/spl/spl-proc.c:28:0:
/var/lib/dkms/spl/0.7.6/build/include/sys/kstat.h:124:1: error: non-constifiable type ‘struct kstat_s’ has field with 'do_const' attribute
 };
 ^
/var/lib/dkms/spl/0.7.6/build/include/sys/kstat.h:121:19: note: type ‘struct kstat_s’ has field ‘ks_raw_ops’ with 'do_const' attribute
  kstat_raw_ops_t  ks_raw_ops;                /* ops table for raw type */
                   ^~~~~~~~~~
make[6]: *** [/usr/src/linux-4.14.19-grsec/scripts/Makefile.build:320: /var/lib/dkms/spl/0.7.6/build/module/spl/spl-proc.o] Error 1

**Comment by behlendorf** [comment]
Closing.  @emcepe now that the spl and zfs repositories have been merged  it would be great if you could try and build the zfs master branch on a grsec kernel and open an issue on the zfsonlinux/zfs issue tracker if needed.
