### ISSUE TITLE
SPL fails to build against Manjaro/Arch Linux 4.15.5-1

### ISSUE THREAD

**Issue by grizzlyfred** [zfsonlinux/spl#689]
What is wrong here?
`/var/lib/dkms/spl/0.7.5/build/module/spl/spl-taskq.c: in function »taskq_dispatch«:
/var/lib/dkms/spl/0.7.5/build/module/spl/spl-taskq.c:593:16: Error: »struct timer_list« has no Element named »data«
  t->tqent_timer.data = 0;
                ^
`
I have issues with my drives, so I decided to rebuild for manjaro's 4.9 LTS, 4.14 LTS and 4.15. via dkms, and 4.15 fails.

**Comment by EvanPurkhiser** [comment]
0.7.5 is an older version of the spl, see the [comments on the AUR package](https://aur.archlinux.org/packages/spl-dkms/).

**Comment by kpande** [comment]
this is not a support forum, please close this.

**Comment by behlendorf** [comment]
Closing, resolved in [0.7.6](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.6).
