### ISSUE TITLE
Unable to configure on ARM Cortex-A53 (RK3328)

### ISSUE THREAD

**Issue by fossxplorer** [zfsonlinux/spl#692]
I'm trying to compile spl on my RK3328 Android box running Armbian, but it stops with the following error:

checking whether spec files are available... yes (rpm/generic/*.spec.in)
checking whether dpkg is available... yes (1.18.4)
checking whether dpkg-buildpackage is available... yes (1.18.4.)
checking whether alien is available... yes (8.95)
checking spl config... all
checking kernel source directory... /usr/src/linux-headers-4.4.77-rk3328
checking kernel build directory... /usr/src/linux-headers-4.4.77-rk3328
checking kernel source version... 4.4.77-rk3328
checking kernel file name for module symbols... Module.symvers
checking whether debugging is enabled... no
checking whether basic kmem accounting is enabled... no
checking whether detailed kmem tracking is enabled... no
checking whether modules can be built... no
configure: error: *** Unable to build an empty module.
root@rock64:~/tmp/spl-spl-0.7.6# 

root@rock64:# uname -a
Linux rock64 4.4.77-rk3328 #29 SMP Mon Nov 20 03:26:28 CET 2017 aarch64 aarch64 aarch64 GNU/Linux
root@rock64:~/tmp# 
root@rock64:~/tmp# lscpu 
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
CPU max MHz:           1296.0000
CPU min MHz:           408.0000
Hypervisor vendor:     (null)
Virtualization type:   full
root@rock64:~/tmp# 

Any hints would be great :)

**Comment by behlendorf** [comment]
@fossxplorer you need to make sure the matching kernel headers for the running kernel are installed.
