### ISSUE TITLE
ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)

### ISSUE THREAD

**Issue by Skorpeo** [zfsonlinux/spl#693]
Installation of  zfs on a new machine fails.  After command modprobe zfs it fails with error:

ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)

dmesg shows following errors:

[ 1570.132904] spl: loading out-of-tree module taints kernel.
[ 1570.133083] spl: module verification failed: signature and/or required key missing - tainting kernel
[ 1570.133324] spl: Unknown symbol __x86_indirect_thunk_rax (err 0)
[ 1570.133384] spl: Unknown symbol __x86_indirect_thunk_rdx (err 0)
[ 1570.133462] spl: Unknown symbol __x86_indirect_thunk_r14 (err 0)
[ 1570.133511] spl: Unknown symbol __x86_indirect_thunk_r13 (err 0)
[ 1570.133609] spl: Unknown symbol __x86_indirect_thunk_r12 (err 0)
[ 1570.133649] spl: Unknown symbol __x86_indirect_thunk_r8 (err 0)

This is on centos 7 with kernel 3.10.0-693.21.1.  I am installing using following commands which used to work in the past:

yum -y install epel-release
yum -y install http://download.zfsonlinux.org/epel/zfs-release.el7_4.noarch.rpm
yum -y install zfs 
modprobe zfs

**Comment by Skorpeo** [comment]
resolved via reboot

**Comment by kpande** [comment]
next time, a) don't delete the text that is telling you what's required for a bug report, and b) don't ask for distribution packaging help on the bug tracker, as it's not a bug. use the mailing list, or IRC.

**Comment by Skorpeo** [comment]
ok thanks and apologies
