### ISSUE TITLE
Is 'CONFIG_TRIM_UNUSED_KSYMS' necessary when spl and zfs are built into the kernel?

### ISSUE THREAD

**Issue by twoertwein** [zfsonlinux/spl#694]
Is it necessary to have `CONFIG_TRIM_UNUSED_KSYMS` disabled when ZFS and SPL are both compiled into the kernel? If it is possible to keep `CONFIG_TRIM_UNUSED_KSYMS` enabled when both are compiled into the kernel, it would be nice to have an option for `configure` to disable this check.

**Comment by behlendorf** [comment]
@twoertwein this could probably be relaxed for the builtin case.  You can check if this is the case by commenting out the `SPL_AC_CONFIG_TRIM_UNUSED_KSYMS` check on line 27 in `config/spl-build.m4`.  Patches welcome!

**Comment by twoertwein** [comment]
it builds and works perfectly even when `CONFIG_TRIM_UNUSED_KSYMS` is enabled (I called `make menuconfig` a second time to re-enable it). I think people who build ZFS into the kernel should be responsible to re-enable `CONFIG_TRIM_UNUSED_KSYMS` themselves. Except through a new option, SPL wouldn't know whether it will be built into the kernel.
