### ISSUE TITLE
Compatibility request for linux 4.18

### ISSUE THREAD

**Issue by krrk** [zfsonlinux/spl#706]
I cannot build spl using the latest rc kernel from Ubuntu: `4.18.0-041800rc3-generic`.

Here is the error.
```
  CC [M]  spl/module/splat/splat-list.o
spl/module/spl/spl-vnode.c: In function ‘vn_getattr’:
spl/module/spl/spl-vnode.c:308:16: error: incompatible types when assigning to type ‘struct timespec’ from type ‘struct timespec64’
  vap->va_atime = stat.atime;
                ^
spl/module/spl/spl-vnode.c:309:16: error: incompatible types when assigning to typee ‘struct timespec64’
  vap->va_mtime = stat.mtime;
                ^
spl/module/spl/spl-vnode.c:310:16: error: incompatible types when assigning to typee ‘struct timespec64’
  vap->va_ctime = stat.ctime;
```

**Comment by gmelikov** [comment]
What is zfs and spl packages versions?

Stable branch is not compatible with 4.18 yet, please wait for next release https://github.com/zfsonlinux/zfs/releases

**Comment by krrk** [comment]
I am using commit 1149b62d  (HEAD~1). This is just before preparing the
repository for merging with zfs.

**Comment by gmelikov** [comment]
@krrk please see https://github.com/zfsonlinux/zfs/commit/6413c95fbd88dc06ae57e50398b8530a17d0c7d3 , it's already fixed in master.

Closed as fixed.

**Comment by behlendorf** [comment]
We expect to backport the 4.18 fixes for the 0.7.10 point release.

**Comment by Nikratio** [comment]
When is the next release planned? The previous releases seem to have been monthly, but the last one was in May.

**Comment by tonyhutter** [comment]
Apoligies @Nikratio, I've been slow on getting the next release out since I've been on baby bonding leave (and still am).  I'd like to have the next release out before the OpenZFS conference on Sept 10th.

**Comment by Nikratio** [comment]
Congratulations! I hope everyone is well.

Could you say a few words about the release procedure? Are you simply taking a snapshot of master, or is there an extensive testing phase? I'm trying to decide if I can risk to compile from Git for now...

**Comment by tonyhutter** [comment]
I cherry pick from all the patches from the project page (https://github.com/zfsonlinux/zfs/projects/18) into the zfs-0.7-release branch, build/test them, and if everything looks good, build the RPMs and release it.

If you're just trying to get something stable working on the latest kernel *right now*, then checkout the zfs-0.7-release branch, and apply any compatibility patches until it builds for you.
