### ISSUE TITLE
Building on aarch64 required more up to date config.guess and config.sub

### ISSUE THREAD

**Issue by gordan-bobic** [zfsonlinux/spl#712]
Building on aarch64 required more up to date config.guess and config.sub. Without it ./configure fails early on because it cannot figure out the build architecture. After updating those two files from upstream sources suggested, configure completes.

Observed on 0.7.12 on aarch64 CentOS.

**Comment by crocket** [comment]
How can I do that? I cannot build spl on aarch64. In my case, the error is

```
configure:15731: cp conftest.c build && make modules -C /usr/src/linux-4.19.9999-raspberrypi EXTRA_CFLAGS=-Werror-implicit-function-declaration   M=/var/tmp/portage/sys-kernel/spl-0.7.13/work/spl-0.7.13/build
/bin/sh: scripts/basic/fixdep: No such file or directory
```

It turns out that /usr/src/linux-4.19.9999-raspberrypi/scripts/basic/fixdep is an x86-64 executable that cannot be executed in aarch64 chroot.

**Comment by gordan-bobic** [comment]
It sounds like your kernel package is broken. You'll have to resolve that first.

I may soon start publishing a 4.9.x kernel rpm package for aarch64 that, with a bit of luck, should also work on RPi 3, but it may be some days/weeks before I have a chance to test that on my Pi (my main platform is Gigabyte MP30-AR0). But that has nothing to do with ZFS...

**Comment by crocket** [comment]
I had to execute `make scripts` in /usr/src/linux before compiling spl.

**Comment by gordan-bobic** [comment]
Ah, awesome. So this can be closed?

**Comment by behlendorf** [comment]
Closing. The SPL has been incorporated in to the ZFS repository.
