### ISSUE TITLE
configure fails on an aarch64 chroot.

### ISSUE THREAD

**Issue by crocket** [zfsonlinux/spl#714]
```
configure:15731: cp conftest.c build && make modules -C /usr/src/linux-4.19.9999-raspberrypi EXTRA_CFLAGS=-Werror-implicit-function-declaration   M=/var/tmp/portage/sys-kernel/spl-0.7.13/work/spl-0.7.13/build
/bin/sh: scripts/basic/fixdep: No such file or directory
```

It turns out that /usr/src/linux-4.19.9999-raspberrypi/scripts/basic/fixdep is an x86-64 executable that cannot be executed in an aarch64 chroot. When I execute /usr/src/linux-4.19.9999-raspberrypi/scripts/basic/fixdep, I see the following error.

```
bash: ./fixdep: No such file or directory
```

It turns out that I had to execute `make scripts` in /usr/src/linux-4.19.9999-raspberrypi to work around the issue.

`make scripts` replaces x86-64 executables with aarch64 executables in /usr/src/linux-x.x.x/scripts

**Comment by behlendorf** [comment]
Closing. The SPL has been incorporated in to the ZFS repository.
