### ISSUE TITLE
Cannot compile on kernel 3.2 PPC64

### ISSUE THREAD

**Issue by tensor5** [zfsonlinux/spl#87]
CC [M]  /home/nicola/PS3/openwrt/trunk/build_dir/target-powerpc_uClibc-0.9.33/spl-git/module/spl/../../module/spl/spl-debug.o
In file included from /home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu.h:191:0,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/lppaca.h:38,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/paca.h:21,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/hw_irq.h:17,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/irqflags.h:11,
                 from include/linux/irqflags.h:15,
                 from include/linux/spinlock.h:53,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:4,
                 from include/linux/kmod.h:22,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/target-powerpc_uClibc-0.9.33/spl-git/module/spl/../../module/spl/spl-debug.c:27:
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h: In function 'hpte_encode_v':
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:194:2: warning: left shift count >= width of type [enabled by default]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h: In function 'hpt_va':
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:226:2: warning: left shift count >= width of type [enabled by default]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h: In function 'hpt_hash':
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:241:3: warning: right shift count >= width of type [enabled by default]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h: In function 'get_kernel_vsid':
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:464:10: error: 'SID_SHIFT' undeclared (first use in this function)
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:464:10: note: each undeclared identifier is reported only once for each function it appears in
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:464:3: warning: right shift count >= width of type [enabled by default]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:464:3: warning: left shift count >= width of type [enabled by default]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:464:3: warning: right shift count >= width of type [enabled by default]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:464:3: warning: left shift count >= width of type [enabled by default]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:465:9: error: 'SID_SHIFT_1T' undeclared (first use in this function)
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h: In function 'user_segment_size':
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:472:22: error: 'SID_SHIFT_1T' undeclared (first use in this function)
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h: In function 'get_vsid':
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:482:10: error: 'SID_SHIFT' undeclared (first use in this function)
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:482:3: warning: right shift count >= width of type [enabled by default]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:482:3: warning: left shift count >= width of type [enabled by default]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:482:3: warning: right shift count >= width of type [enabled by default]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:482:3: warning: left shift count >= width of type [enabled by default]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/mmu-hash64.h:484:9: error: 'SID_SHIFT_1T' undeclared (first use in this function)
In file included from include/linux/atomic.h:100:0,
                 from include/linux/spinlock.h:387,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:4,
                 from include/linux/kmod.h:22,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/target-powerpc_uClibc-0.9.33/spl-git/module/spl/../../module/spl/spl-debug.c:27:
include/asm-generic/atomic-long.h: In function 'atomic_long_read':
include/asm-generic/atomic-long.h:31:2: error: implicit declaration of function 'atomic64_read' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_set':
include/asm-generic/atomic-long.h:38:2: error: implicit declaration of function 'atomic64_set' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_inc':
include/asm-generic/atomic-long.h:45:2: error: implicit declaration of function 'atomic64_inc' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_dec':
include/asm-generic/atomic-long.h:52:2: error: implicit declaration of function 'atomic64_dec' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_add':
include/asm-generic/atomic-long.h:59:2: error: implicit declaration of function 'atomic64_add' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_sub':
include/asm-generic/atomic-long.h:66:2: error: implicit declaration of function 'atomic64_sub' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_sub_and_test':
include/asm-generic/atomic-long.h:73:2: error: implicit declaration of function 'atomic64_sub_and_test' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_dec_and_test':
include/asm-generic/atomic-long.h:80:2: error: implicit declaration of function 'atomic64_dec_and_test' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_inc_and_test':
include/asm-generic/atomic-long.h:87:2: error: implicit declaration of function 'atomic64_inc_and_test' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_add_negative':
include/asm-generic/atomic-long.h:94:2: error: implicit declaration of function 'atomic64_add_negative' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_add_return':
include/asm-generic/atomic-long.h:101:2: error: implicit declaration of function 'atomic64_add_return' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_sub_return':
include/asm-generic/atomic-long.h:108:2: error: implicit declaration of function 'atomic64_sub_return' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_inc_return':
include/asm-generic/atomic-long.h:115:2: error: implicit declaration of function 'atomic64_inc_return' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_dec_return':
include/asm-generic/atomic-long.h:122:2: error: implicit declaration of function 'atomic64_dec_return' [-Werror=implicit-function-declaration]
include/asm-generic/atomic-long.h: In function 'atomic_long_add_unless':
include/asm-generic/atomic-long.h:129:2: error: implicit declaration of function 'atomic64_add_unless' [-Werror=implicit-function-declaration]
In file included from include/linux/gfp.h:4:0,
                 from include/linux/kmod.h:22,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/target-powerpc_uClibc-0.9.33/spl-git/module/spl/../../module/spl/spl-debug.c:27:
include/linux/mmzone.h: At top level:
include/linux/mmzone.h:974:2: error: #error Allocator MAX_ORDER exceeds SECTION_SIZE
In file included from /home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/pgtable.h:23:0,
                 from include/linux/mm.h:43,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/target-powerpc_uClibc-0.9.33/spl-git/module/spl/../../module/spl/spl-debug.c:28:
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/pgtable-ppc64.h:30:50: warning: "SID_SHIFT" is not defined [-Wundef]
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/pgtable-ppc64.h:31:2: error: #error TASK_SIZE_USER64 exceeds user VSID range
In file included from /home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/pgtable.h:23:0,
                 from include/linux/mm.h:43,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/target-powerpc_uClibc-0.9.33/spl-git/module/spl/../../module/spl/spl-debug.c:28:
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/pgtable-ppc64.h: In function 'find_linux_pte':
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/pgtable-ppc64.h:368:2: warning: right shift count >= width of type [enabled by default]
In file included from /home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/cputime.h:29:0,
                 from include/linux/sched.h:69,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/uaccess.h:7,
                 from include/linux/uaccess.h:5,
                 from include/linux/highmem.h:7,
                 from include/linux/pagemap.h:10,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/target-powerpc_uClibc-0.9.33/spl-git/module/spl/../../module/spl/spl-debug.c:30:
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/time.h: In function 'get_tb':
/home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/time.h:111:2: error: implicit declaration of function 'mftb' [-Werror=implicit-function-declaration]
In file included from /home/nicola/PS3/openwrt/trunk/build_dir/linux-ps3_petitboot/linux-3.2.11/arch/powerpc/include/asm/uaccess.h:7:0,
                 from include/linux/uaccess.h:5,
                 from include/linux/highmem.h:7,
                 from include/linux/pagemap.h:10,
                 from /home/nicola/PS3/openwrt/trunk/build_dir/target-powerpc_uClibc-0.9.33/spl-git/module/spl/../../module/spl/spl-debug.c:30:
include/linux/sched.h: At top level:
include/linux/sched.h:200:3: error: implicit declaration of function '__ilog2_u64' [-Werror=implicit-function-declaration]
/home/nicola/PS3/openwrt/trunk/build_dir/target-powerpc_uClibc-0.9.33/spl-git/module/spl/../../module/spl/spl-debug.c: In function 'spl_debug_dump_all_pages':
/home/nicola/PS3/openwrt/trunk/build_dir/target-powerpc_uClibc-0.9.33/spl-git/module/spl/../../module/spl/spl-debug.c:966:9: warning: passing argument 2 of 'vfs_fsync' makes integer from pointer without a cast [enabled by default]
include/linux/fs.h:2256:12: note: expected 'int' but argument is of type 'struct dentry *'
/home/nicola/PS3/openwrt/trunk/build_dir/target-powerpc_uClibc-0.9.33/spl-git/module/spl/../../module/spl/spl-debug.c:966:9: error: too many arguments to function 'vfs_fsync'
include/linux/fs.h:2256:12: note: declared here
cc1: some warnings being treated as errors

**Comment by mailinglists35** [comment]
@tensor5 have you managed to produce a useable build for openwrt? if yes, could you post instructions?

**Comment by tensor5** [comment]
No, haven't tried since I opened the bug. I lost interest in that platform but I may give it a shot if you are.

**Comment by mailinglists35** [comment]
i have a netgear wndr4300 router and was curious if this 128mb ram and mips cpu device could handle a single 1Tb usb drive formatted with zfs + snapshots

**Comment by tensor5** [comment]
I originally wanted to try ZFS on a PS3, which has 256mb ram, but then I ended up using btrfs.
I'll try and see if it compiles, when I have some time.

**Comment by tensor5** [comment]
I tried today after a long time, and I was able to cross compile spl and zfs 0.6.4 for powerpc64 using linux 4.0. I haven't tested it, though.

**Comment by behlendorf** [comment]
@tensor5 that's good news.  If you get a chance to load the modules and verify they work let us know!

**Comment by mailinglists35** [comment]
@tensor5 wow wow wow!
would you mind sharing the result or (preferrably) the build steps?

**Comment by tensor5** [comment]
I had to edit the configure script in order to allow cross compilation; other then that it was just configure and make. I'll post the details soon.

**Comment by behlendorf** [comment]
Resolved and a ppc64 builder was added to prevent future regressions.

http://build.zfsonlinux.org/builders/Debian%208%20ppc64%20%28BUILD%29
